// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddFriendArgs {
    pub player_entity_id: u64,
}

impl From<AddFriendArgs> for super::Reducer {
    fn from(args: AddFriendArgs) -> Self {
        Self::AddFriend {
            player_entity_id: args.player_entity_id,
}
}
}

impl __sdk::InModule for AddFriendArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_friend`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_friend {
    /// Request that the remote module invoke the reducer `add_friend` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_friend:add_friend_then`] to run a callback after the reducer completes.
    fn add_friend(&self, player_entity_id: u64,
) -> __sdk::Result<()> {
        self.add_friend_then(player_entity_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_friend` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_friend_then(
        &self,
        player_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_friend for super::RemoteReducers {
    fn add_friend_then(
        &self,
        player_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddFriendArgs { player_entity_id,  }, callback)
    }
}

