// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminAddOrUpdateModerationConsequenceArgs {
    pub id: u64,
    pub point_threshold: i32,
    pub consequence_type: u8,
    pub duration: i32,
    pub flag_level_code: u8,
}

impl From<AdminAddOrUpdateModerationConsequenceArgs> for super::Reducer {
    fn from(args: AdminAddOrUpdateModerationConsequenceArgs) -> Self {
        Self::AdminAddOrUpdateModerationConsequence {
            id: args.id,
            point_threshold: args.point_threshold,
            consequence_type: args.consequence_type,
            duration: args.duration,
            flag_level_code: args.flag_level_code,
}
}
}

impl __sdk::InModule for AdminAddOrUpdateModerationConsequenceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_add_or_update_moderation_consequence`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_add_or_update_moderation_consequence {
    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_consequence` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_add_or_update_moderation_consequence:admin_add_or_update_moderation_consequence_then`] to run a callback after the reducer completes.
    fn admin_add_or_update_moderation_consequence(&self, id: u64,
point_threshold: i32,
consequence_type: u8,
duration: i32,
flag_level_code: u8,
) -> __sdk::Result<()> {
        self.admin_add_or_update_moderation_consequence_then(id, point_threshold, consequence_type, duration, flag_level_code,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_consequence` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_add_or_update_moderation_consequence_then(
        &self,
        id: u64,
point_threshold: i32,
consequence_type: u8,
duration: i32,
flag_level_code: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_add_or_update_moderation_consequence for super::RemoteReducers {
    fn admin_add_or_update_moderation_consequence_then(
        &self,
        id: u64,
point_threshold: i32,
consequence_type: u8,
duration: i32,
flag_level_code: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminAddOrUpdateModerationConsequenceArgs { id, point_threshold, consequence_type, duration, flag_level_code,  }, callback)
    }
}

