// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminPopulatePlayerSkillsArgs {
    pub identity_skill_stacks_row: String,
}

impl From<AdminPopulatePlayerSkillsArgs> for super::Reducer {
    fn from(args: AdminPopulatePlayerSkillsArgs) -> Self {
        Self::AdminPopulatePlayerSkills {
            identity_skill_stacks_row: args.identity_skill_stacks_row,
}
}
}

impl __sdk::InModule for AdminPopulatePlayerSkillsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_populate_player_skills`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_populate_player_skills {
    /// Request that the remote module invoke the reducer `admin_populate_player_skills` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_populate_player_skills:admin_populate_player_skills_then`] to run a callback after the reducer completes.
    fn admin_populate_player_skills(&self, identity_skill_stacks_row: String,
) -> __sdk::Result<()> {
        self.admin_populate_player_skills_then(identity_skill_stacks_row,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_populate_player_skills` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_populate_player_skills_then(
        &self,
        identity_skill_stacks_row: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_populate_player_skills for super::RemoteReducers {
    fn admin_populate_player_skills_then(
        &self,
        identity_skill_stacks_row: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminPopulatePlayerSkillsArgs { identity_skill_stacks_row,  }, callback)
    }
}

