// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminLogModerationActionArgs {
    pub report_entity_id: u64,
    pub reported_player_entity_id: u64,
    pub admin_name: String,
    pub reported_player_username: String,
    pub action_type: String,
    pub moderation_notice: String,
    pub details: String,
}

impl From<AdminLogModerationActionArgs> for super::Reducer {
    fn from(args: AdminLogModerationActionArgs) -> Self {
        Self::AdminLogModerationAction {
            report_entity_id: args.report_entity_id,
            reported_player_entity_id: args.reported_player_entity_id,
            admin_name: args.admin_name,
            reported_player_username: args.reported_player_username,
            action_type: args.action_type,
            moderation_notice: args.moderation_notice,
            details: args.details,
}
}
}

impl __sdk::InModule for AdminLogModerationActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_log_moderation_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_log_moderation_action {
    /// Request that the remote module invoke the reducer `admin_log_moderation_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_log_moderation_action:admin_log_moderation_action_then`] to run a callback after the reducer completes.
    fn admin_log_moderation_action(&self, report_entity_id: u64,
reported_player_entity_id: u64,
admin_name: String,
reported_player_username: String,
action_type: String,
moderation_notice: String,
details: String,
) -> __sdk::Result<()> {
        self.admin_log_moderation_action_then(report_entity_id, reported_player_entity_id, admin_name, reported_player_username, action_type, moderation_notice, details,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_log_moderation_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_log_moderation_action_then(
        &self,
        report_entity_id: u64,
reported_player_entity_id: u64,
admin_name: String,
reported_player_username: String,
action_type: String,
moderation_notice: String,
details: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_log_moderation_action for super::RemoteReducers {
    fn admin_log_moderation_action_then(
        &self,
        report_entity_id: u64,
reported_player_entity_id: u64,
admin_name: String,
reported_player_username: String,
action_type: String,
moderation_notice: String,
details: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminLogModerationActionArgs { report_entity_id, reported_player_entity_id, admin_name, reported_player_username, action_type, moderation_notice, details,  }, callback)
    }
}

