// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::region_sign_in_parameters_type::RegionSignInParameters;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUpdateSignInParametersArgs {
    pub region_sign_in_parameters: RegionSignInParameters,
    pub region: u8,
}

impl From<AdminUpdateSignInParametersArgs> for super::Reducer {
    fn from(args: AdminUpdateSignInParametersArgs) -> Self {
        Self::AdminUpdateSignInParameters {
            region_sign_in_parameters: args.region_sign_in_parameters,
            region: args.region,
}
}
}

impl __sdk::InModule for AdminUpdateSignInParametersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_update_sign_in_parameters`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_update_sign_in_parameters {
    /// Request that the remote module invoke the reducer `admin_update_sign_in_parameters` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_update_sign_in_parameters:admin_update_sign_in_parameters_then`] to run a callback after the reducer completes.
    fn admin_update_sign_in_parameters(&self, region_sign_in_parameters: RegionSignInParameters,
region: u8,
) -> __sdk::Result<()> {
        self.admin_update_sign_in_parameters_then(region_sign_in_parameters, region,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_update_sign_in_parameters` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_update_sign_in_parameters_then(
        &self,
        region_sign_in_parameters: RegionSignInParameters,
region: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_update_sign_in_parameters for super::RemoteReducers {
    fn admin_update_sign_in_parameters_then(
        &self,
        region_sign_in_parameters: RegionSignInParameters,
region: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminUpdateSignInParametersArgs { region_sign_in_parameters, region,  }, callback)
    }
}

