// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminReplaceIdentityArgs {
    pub old_identity: String,
    pub new_identity: String,
}

impl From<AdminReplaceIdentityArgs> for super::Reducer {
    fn from(args: AdminReplaceIdentityArgs) -> Self {
        Self::AdminReplaceIdentity {
            old_identity: args.old_identity,
            new_identity: args.new_identity,
}
}
}

impl __sdk::InModule for AdminReplaceIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_replace_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_replace_identity {
    /// Request that the remote module invoke the reducer `admin_replace_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_replace_identity:admin_replace_identity_then`] to run a callback after the reducer completes.
    fn admin_replace_identity(&self, old_identity: String,
new_identity: String,
) -> __sdk::Result<()> {
        self.admin_replace_identity_then(old_identity, new_identity,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_replace_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_replace_identity_then(
        &self,
        old_identity: String,
new_identity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_replace_identity for super::RemoteReducers {
    fn admin_replace_identity_then(
        &self,
        old_identity: String,
new_identity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminReplaceIdentityArgs { old_identity, new_identity,  }, callback)
    }
}

