// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminAddOrUpdateWordReplacementArgs {
    pub id: u64,
    pub words_to_replace: Vec::<String>,
    pub text_replacement: String,
    pub is_developer_url_replacement: bool,
}

impl From<AdminAddOrUpdateWordReplacementArgs> for super::Reducer {
    fn from(args: AdminAddOrUpdateWordReplacementArgs) -> Self {
        Self::AdminAddOrUpdateWordReplacement {
            id: args.id,
            words_to_replace: args.words_to_replace,
            text_replacement: args.text_replacement,
            is_developer_url_replacement: args.is_developer_url_replacement,
}
}
}

impl __sdk::InModule for AdminAddOrUpdateWordReplacementArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_add_or_update_word_replacement`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_add_or_update_word_replacement {
    /// Request that the remote module invoke the reducer `admin_add_or_update_word_replacement` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_add_or_update_word_replacement:admin_add_or_update_word_replacement_then`] to run a callback after the reducer completes.
    fn admin_add_or_update_word_replacement(&self, id: u64,
words_to_replace: Vec::<String>,
text_replacement: String,
is_developer_url_replacement: bool,
) -> __sdk::Result<()> {
        self.admin_add_or_update_word_replacement_then(id, words_to_replace, text_replacement, is_developer_url_replacement,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_add_or_update_word_replacement` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_add_or_update_word_replacement_then(
        &self,
        id: u64,
words_to_replace: Vec::<String>,
text_replacement: String,
is_developer_url_replacement: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_add_or_update_word_replacement for super::RemoteReducers {
    fn admin_add_or_update_word_replacement_then(
        &self,
        id: u64,
words_to_replace: Vec::<String>,
text_replacement: String,
is_developer_url_replacement: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminAddOrUpdateWordReplacementArgs { id, words_to_replace, text_replacement, is_developer_url_replacement,  }, callback)
    }
}

