// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRemoveFlaggedWordArgs {
    pub id: u64,
}

impl From<AdminRemoveFlaggedWordArgs> for super::Reducer {
    fn from(args: AdminRemoveFlaggedWordArgs) -> Self {
        Self::AdminRemoveFlaggedWord { id: args.id }
    }
}

impl __sdk::InModule for AdminRemoveFlaggedWordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_remove_flagged_word`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_remove_flagged_word {
    /// Request that the remote module invoke the reducer `admin_remove_flagged_word` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_remove_flagged_word:admin_remove_flagged_word_then`] to run a callback after the reducer completes.
    fn admin_remove_flagged_word(&self, id: u64) -> __sdk::Result<()> {
        self.admin_remove_flagged_word_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_remove_flagged_word` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_remove_flagged_word_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_remove_flagged_word for super::RemoteReducers {
    fn admin_remove_flagged_word_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminRemoveFlaggedWordArgs { id }, callback)
    }
}
