// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminCreateDirectChatMessageArgs {
    pub username: String,
    pub title_id: i32,
    pub receiver_id: u64,
    pub new_message_text: String,
}

impl From<AdminCreateDirectChatMessageArgs> for super::Reducer {
    fn from(args: AdminCreateDirectChatMessageArgs) -> Self {
        Self::AdminCreateDirectChatMessage {
            username: args.username,
            title_id: args.title_id,
            receiver_id: args.receiver_id,
            new_message_text: args.new_message_text,
}
}
}

impl __sdk::InModule for AdminCreateDirectChatMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_create_direct_chat_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_create_direct_chat_message {
    /// Request that the remote module invoke the reducer `admin_create_direct_chat_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_create_direct_chat_message:admin_create_direct_chat_message_then`] to run a callback after the reducer completes.
    fn admin_create_direct_chat_message(&self, username: String,
title_id: i32,
receiver_id: u64,
new_message_text: String,
) -> __sdk::Result<()> {
        self.admin_create_direct_chat_message_then(username, title_id, receiver_id, new_message_text,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_create_direct_chat_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_create_direct_chat_message_then(
        &self,
        username: String,
title_id: i32,
receiver_id: u64,
new_message_text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_create_direct_chat_message for super::RemoteReducers {
    fn admin_create_direct_chat_message_then(
        &self,
        username: String,
title_id: i32,
receiver_id: u64,
new_message_text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminCreateDirectChatMessageArgs { username, title_id, receiver_id, new_message_text,  }, callback)
    }
}

