// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminAddOrUpdateModerationFlagLevelThresholdArgs {
    pub flag_level: u8,
    pub point_threshold: i32,
}

impl From<AdminAddOrUpdateModerationFlagLevelThresholdArgs> for super::Reducer {
    fn from(args: AdminAddOrUpdateModerationFlagLevelThresholdArgs) -> Self {
        Self::AdminAddOrUpdateModerationFlagLevelThreshold {
            flag_level: args.flag_level,
            point_threshold: args.point_threshold,
        }
    }
}

impl __sdk::InModule for AdminAddOrUpdateModerationFlagLevelThresholdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_add_or_update_moderation_flag_level_threshold`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_add_or_update_moderation_flag_level_threshold {
    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_flag_level_threshold` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_add_or_update_moderation_flag_level_threshold:admin_add_or_update_moderation_flag_level_threshold_then`] to run a callback after the reducer completes.
    fn admin_add_or_update_moderation_flag_level_threshold(
        &self,
        flag_level: u8,
        point_threshold: i32,
    ) -> __sdk::Result<()> {
        self.admin_add_or_update_moderation_flag_level_threshold_then(
            flag_level,
            point_threshold,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_flag_level_threshold` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_add_or_update_moderation_flag_level_threshold_then(
        &self,
        flag_level: u8,
        point_threshold: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_add_or_update_moderation_flag_level_threshold for super::RemoteReducers {
    fn admin_add_or_update_moderation_flag_level_threshold_then(
        &self,
        flag_level: u8,
        point_threshold: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminAddOrUpdateModerationFlagLevelThresholdArgs {
                flag_level,
                point_threshold,
            },
            callback,
        )
    }
}
