// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminGrantShardsArgs {
    pub identity: String,
    pub amount: i32,
}

impl From<AdminGrantShardsArgs> for super::Reducer {
    fn from(args: AdminGrantShardsArgs) -> Self {
        Self::AdminGrantShards {
            identity: args.identity,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for AdminGrantShardsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_grant_shards`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_grant_shards {
    /// Request that the remote module invoke the reducer `admin_grant_shards` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_grant_shards:admin_grant_shards_then`] to run a callback after the reducer completes.
    fn admin_grant_shards(&self, identity: String, amount: i32) -> __sdk::Result<()> {
        self.admin_grant_shards_then(identity, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_grant_shards` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_grant_shards_then(
        &self,
        identity: String,
        amount: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_grant_shards for super::RemoteReducers {
    fn admin_grant_shards_then(
        &self,
        identity: String,
        amount: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminGrantShardsArgs { identity, amount }, callback)
    }
}
