// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUpdateRegionExplorationInfoArgs {
    pub region_id: u8,
    pub counts_toward_achievements: bool,
}

impl From<AdminUpdateRegionExplorationInfoArgs> for super::Reducer {
    fn from(args: AdminUpdateRegionExplorationInfoArgs) -> Self {
        Self::AdminUpdateRegionExplorationInfo {
            region_id: args.region_id,
            counts_toward_achievements: args.counts_toward_achievements,
}
}
}

impl __sdk::InModule for AdminUpdateRegionExplorationInfoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_update_region_exploration_info`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_update_region_exploration_info {
    /// Request that the remote module invoke the reducer `admin_update_region_exploration_info` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_update_region_exploration_info:admin_update_region_exploration_info_then`] to run a callback after the reducer completes.
    fn admin_update_region_exploration_info(&self, region_id: u8,
counts_toward_achievements: bool,
) -> __sdk::Result<()> {
        self.admin_update_region_exploration_info_then(region_id, counts_toward_achievements,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_update_region_exploration_info` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_update_region_exploration_info_then(
        &self,
        region_id: u8,
counts_toward_achievements: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_update_region_exploration_info for super::RemoteReducers {
    fn admin_update_region_exploration_info_then(
        &self,
        region_id: u8,
counts_toward_achievements: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminUpdateRegionExplorationInfoArgs { region_id, counts_toward_achievements,  }, callback)
    }
}

