// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUpdateReportModerationConfigArgs {
    pub model: String,
    pub model_double_check: String,
    pub model_translate: String,
    pub offense_count_window_minutes: f32,
    pub min_minutes_between_offenses: f32,
    pub reportable_message_max_age: i32,
    pub count_admin_moderation_actions: bool,
    pub discord_webhook_url_user_reports: String,
}

impl From<AdminUpdateReportModerationConfigArgs> for super::Reducer {
    fn from(args: AdminUpdateReportModerationConfigArgs) -> Self {
        Self::AdminUpdateReportModerationConfig {
            model: args.model,
            model_double_check: args.model_double_check,
            model_translate: args.model_translate,
            offense_count_window_minutes: args.offense_count_window_minutes,
            min_minutes_between_offenses: args.min_minutes_between_offenses,
            reportable_message_max_age: args.reportable_message_max_age,
            count_admin_moderation_actions: args.count_admin_moderation_actions,
            discord_webhook_url_user_reports: args.discord_webhook_url_user_reports,
        }
    }
}

impl __sdk::InModule for AdminUpdateReportModerationConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_update_report_moderation_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_update_report_moderation_config {
    /// Request that the remote module invoke the reducer `admin_update_report_moderation_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_update_report_moderation_config:admin_update_report_moderation_config_then`] to run a callback after the reducer completes.
    fn admin_update_report_moderation_config(
        &self,
        model: String,
        model_double_check: String,
        model_translate: String,
        offense_count_window_minutes: f32,
        min_minutes_between_offenses: f32,
        reportable_message_max_age: i32,
        count_admin_moderation_actions: bool,
        discord_webhook_url_user_reports: String,
    ) -> __sdk::Result<()> {
        self.admin_update_report_moderation_config_then(
            model,
            model_double_check,
            model_translate,
            offense_count_window_minutes,
            min_minutes_between_offenses,
            reportable_message_max_age,
            count_admin_moderation_actions,
            discord_webhook_url_user_reports,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `admin_update_report_moderation_config` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_update_report_moderation_config_then(
        &self,
        model: String,
        model_double_check: String,
        model_translate: String,
        offense_count_window_minutes: f32,
        min_minutes_between_offenses: f32,
        reportable_message_max_age: i32,
        count_admin_moderation_actions: bool,
        discord_webhook_url_user_reports: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_update_report_moderation_config for super::RemoteReducers {
    fn admin_update_report_moderation_config_then(
        &self,
        model: String,
        model_double_check: String,
        model_translate: String,
        offense_count_window_minutes: f32,
        min_minutes_between_offenses: f32,
        reportable_message_max_age: i32,
        count_admin_moderation_actions: bool,
        discord_webhook_url_user_reports: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminUpdateReportModerationConfigArgs {
                model,
                model_double_check,
                model_translate,
                offense_count_window_minutes,
                min_minutes_between_offenses,
                reportable_message_max_age,
                count_admin_moderation_actions,
                discord_webhook_url_user_reports,
            },
            callback,
        )
    }
}
