// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminBroadcastMsgArgs {
    pub region: u8,
    pub title: String,
    pub message: String,
}

impl From<AdminBroadcastMsgArgs> for super::Reducer {
    fn from(args: AdminBroadcastMsgArgs) -> Self {
        Self::AdminBroadcastMsg {
            region: args.region,
            title: args.title,
            message: args.message,
        }
    }
}

impl __sdk::InModule for AdminBroadcastMsgArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_broadcast_msg`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_broadcast_msg {
    /// Request that the remote module invoke the reducer `admin_broadcast_msg` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_broadcast_msg:admin_broadcast_msg_then`] to run a callback after the reducer completes.
    fn admin_broadcast_msg(&self, region: u8, title: String, message: String) -> __sdk::Result<()> {
        self.admin_broadcast_msg_then(region, title, message, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_broadcast_msg` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_broadcast_msg_then(
        &self,
        region: u8,
        title: String,
        message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_broadcast_msg for super::RemoteReducers {
    fn admin_broadcast_msg_then(
        &self,
        region: u8,
        title: String,
        message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminBroadcastMsgArgs {
                region,
                title,
                message,
            },
            callback,
        )
    }
}
