// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUpdateModerationEnforcementConfigArgs {
    pub moderation_enforcement_active: bool,
    pub chat_moderation_enforcement_active: bool,
    pub username_moderation_enforcement_active: bool,
    pub entity_moderation_enforcement_active: bool,
    pub moderated_entity_name_types: u8,
    pub check_for_links: bool,
    pub check_for_flagged_words: bool,
    pub check_for_context_flagged_words: bool,
    pub delete_flagged_messages: bool,
    pub allow_links_cwl: bool,
    pub title_id_cwl: i32,
    pub http_request_max_retries: i32,
}

impl From<AdminUpdateModerationEnforcementConfigArgs> for super::Reducer {
    fn from(args: AdminUpdateModerationEnforcementConfigArgs) -> Self {
        Self::AdminUpdateModerationEnforcementConfig {
            moderation_enforcement_active: args.moderation_enforcement_active,
            chat_moderation_enforcement_active: args.chat_moderation_enforcement_active,
            username_moderation_enforcement_active: args.username_moderation_enforcement_active,
            entity_moderation_enforcement_active: args.entity_moderation_enforcement_active,
            moderated_entity_name_types: args.moderated_entity_name_types,
            check_for_links: args.check_for_links,
            check_for_flagged_words: args.check_for_flagged_words,
            check_for_context_flagged_words: args.check_for_context_flagged_words,
            delete_flagged_messages: args.delete_flagged_messages,
            allow_links_cwl: args.allow_links_cwl,
            title_id_cwl: args.title_id_cwl,
            http_request_max_retries: args.http_request_max_retries,
        }
    }
}

impl __sdk::InModule for AdminUpdateModerationEnforcementConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_update_moderation_enforcement_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_update_moderation_enforcement_config {
    /// Request that the remote module invoke the reducer `admin_update_moderation_enforcement_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_update_moderation_enforcement_config:admin_update_moderation_enforcement_config_then`] to run a callback after the reducer completes.
    fn admin_update_moderation_enforcement_config(
        &self,
        moderation_enforcement_active: bool,
        chat_moderation_enforcement_active: bool,
        username_moderation_enforcement_active: bool,
        entity_moderation_enforcement_active: bool,
        moderated_entity_name_types: u8,
        check_for_links: bool,
        check_for_flagged_words: bool,
        check_for_context_flagged_words: bool,
        delete_flagged_messages: bool,
        allow_links_cwl: bool,
        title_id_cwl: i32,
        http_request_max_retries: i32,
    ) -> __sdk::Result<()> {
        self.admin_update_moderation_enforcement_config_then(
            moderation_enforcement_active,
            chat_moderation_enforcement_active,
            username_moderation_enforcement_active,
            entity_moderation_enforcement_active,
            moderated_entity_name_types,
            check_for_links,
            check_for_flagged_words,
            check_for_context_flagged_words,
            delete_flagged_messages,
            allow_links_cwl,
            title_id_cwl,
            http_request_max_retries,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `admin_update_moderation_enforcement_config` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_update_moderation_enforcement_config_then(
        &self,
        moderation_enforcement_active: bool,
        chat_moderation_enforcement_active: bool,
        username_moderation_enforcement_active: bool,
        entity_moderation_enforcement_active: bool,
        moderated_entity_name_types: u8,
        check_for_links: bool,
        check_for_flagged_words: bool,
        check_for_context_flagged_words: bool,
        delete_flagged_messages: bool,
        allow_links_cwl: bool,
        title_id_cwl: i32,
        http_request_max_retries: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_update_moderation_enforcement_config for super::RemoteReducers {
    fn admin_update_moderation_enforcement_config_then(
        &self,
        moderation_enforcement_active: bool,
        chat_moderation_enforcement_active: bool,
        username_moderation_enforcement_active: bool,
        entity_moderation_enforcement_active: bool,
        moderated_entity_name_types: u8,
        check_for_links: bool,
        check_for_flagged_words: bool,
        check_for_context_flagged_words: bool,
        delete_flagged_messages: bool,
        allow_links_cwl: bool,
        title_id_cwl: i32,
        http_request_max_retries: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminUpdateModerationEnforcementConfigArgs {
                moderation_enforcement_active,
                chat_moderation_enforcement_active,
                username_moderation_enforcement_active,
                entity_moderation_enforcement_active,
                moderated_entity_name_types,
                check_for_links,
                check_for_flagged_words,
                check_for_context_flagged_words,
                delete_flagged_messages,
                allow_links_cwl,
                title_id_cwl,
                http_request_max_retries,
            },
            callback,
        )
    }
}
