// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminChangeEmpireEmblemArgs {
    pub empire_entity_id: u64,
    pub icon_id: i32,
    pub shape_id: i32,
    pub color_1_id: i32,
    pub color_2_id: i32,
}

impl From<AdminChangeEmpireEmblemArgs> for super::Reducer {
    fn from(args: AdminChangeEmpireEmblemArgs) -> Self {
        Self::AdminChangeEmpireEmblem {
            empire_entity_id: args.empire_entity_id,
            icon_id: args.icon_id,
            shape_id: args.shape_id,
            color_1_id: args.color_1_id,
            color_2_id: args.color_2_id,
}
}
}

impl __sdk::InModule for AdminChangeEmpireEmblemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_change_empire_emblem`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_change_empire_emblem {
    /// Request that the remote module invoke the reducer `admin_change_empire_emblem` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_change_empire_emblem:admin_change_empire_emblem_then`] to run a callback after the reducer completes.
    fn admin_change_empire_emblem(&self, empire_entity_id: u64,
icon_id: i32,
shape_id: i32,
color_1_id: i32,
color_2_id: i32,
) -> __sdk::Result<()> {
        self.admin_change_empire_emblem_then(empire_entity_id, icon_id, shape_id, color_1_id, color_2_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_change_empire_emblem` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_change_empire_emblem_then(
        &self,
        empire_entity_id: u64,
icon_id: i32,
shape_id: i32,
color_1_id: i32,
color_2_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_change_empire_emblem for super::RemoteReducers {
    fn admin_change_empire_emblem_then(
        &self,
        empire_entity_id: u64,
icon_id: i32,
shape_id: i32,
color_1_id: i32,
color_2_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminChangeEmpireEmblemArgs { empire_entity_id, icon_id, shape_id, color_1_id, color_2_id,  }, callback)
    }
}

