// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminPopulateEmpireNamesArgs {
    pub identity_empire_name_row: String,
}

impl From<AdminPopulateEmpireNamesArgs> for super::Reducer {
    fn from(args: AdminPopulateEmpireNamesArgs) -> Self {
        Self::AdminPopulateEmpireNames {
            identity_empire_name_row: args.identity_empire_name_row,
}
}
}

impl __sdk::InModule for AdminPopulateEmpireNamesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_populate_empire_names`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_populate_empire_names {
    /// Request that the remote module invoke the reducer `admin_populate_empire_names` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_populate_empire_names:admin_populate_empire_names_then`] to run a callback after the reducer completes.
    fn admin_populate_empire_names(&self, identity_empire_name_row: String,
) -> __sdk::Result<()> {
        self.admin_populate_empire_names_then(identity_empire_name_row,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_populate_empire_names` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_populate_empire_names_then(
        &self,
        identity_empire_name_row: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_populate_empire_names for super::RemoteReducers {
    fn admin_populate_empire_names_then(
        &self,
        identity_empire_name_row: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminPopulateEmpireNamesArgs { identity_empire_name_row,  }, callback)
    }
}

