// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminAddOrUpdateModerationThresholdArgs {
    pub id: u64,
    pub threshold_type: u8,
    pub category: String,
    pub threshold: f64,
}

impl From<AdminAddOrUpdateModerationThresholdArgs> for super::Reducer {
    fn from(args: AdminAddOrUpdateModerationThresholdArgs) -> Self {
        Self::AdminAddOrUpdateModerationThreshold {
            id: args.id,
            threshold_type: args.threshold_type,
            category: args.category,
            threshold: args.threshold,
        }
    }
}

impl __sdk::InModule for AdminAddOrUpdateModerationThresholdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_add_or_update_moderation_threshold`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_add_or_update_moderation_threshold {
    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_threshold` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_add_or_update_moderation_threshold:admin_add_or_update_moderation_threshold_then`] to run a callback after the reducer completes.
    fn admin_add_or_update_moderation_threshold(
        &self,
        id: u64,
        threshold_type: u8,
        category: String,
        threshold: f64,
    ) -> __sdk::Result<()> {
        self.admin_add_or_update_moderation_threshold_then(
            id,
            threshold_type,
            category,
            threshold,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_threshold` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_add_or_update_moderation_threshold_then(
        &self,
        id: u64,
        threshold_type: u8,
        category: String,
        threshold: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_add_or_update_moderation_threshold for super::RemoteReducers {
    fn admin_add_or_update_moderation_threshold_then(
        &self,
        id: u64,
        threshold_type: u8,
        category: String,
        threshold: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminAddOrUpdateModerationThresholdArgs {
                id,
                threshold_type,
                category,
                threshold,
            },
            callback,
        )
    }
}
