// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::hub_item_type_type::HubItemType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUpdateGrantedHubItemStateArgs {
    pub identity: __sdk::Identity,
    pub item_type: HubItemType,
    pub item_id: i32,
    pub balance: u32,
}

impl From<AdminUpdateGrantedHubItemStateArgs> for super::Reducer {
    fn from(args: AdminUpdateGrantedHubItemStateArgs) -> Self {
        Self::AdminUpdateGrantedHubItemState {
            identity: args.identity,
            item_type: args.item_type,
            item_id: args.item_id,
            balance: args.balance,
}
}
}

impl __sdk::InModule for AdminUpdateGrantedHubItemStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_update_granted_hub_item_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_update_granted_hub_item_state {
    /// Request that the remote module invoke the reducer `admin_update_granted_hub_item_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_update_granted_hub_item_state:admin_update_granted_hub_item_state_then`] to run a callback after the reducer completes.
    fn admin_update_granted_hub_item_state(&self, identity: __sdk::Identity,
item_type: HubItemType,
item_id: i32,
balance: u32,
) -> __sdk::Result<()> {
        self.admin_update_granted_hub_item_state_then(identity, item_type, item_id, balance,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_update_granted_hub_item_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_update_granted_hub_item_state_then(
        &self,
        identity: __sdk::Identity,
item_type: HubItemType,
item_id: i32,
balance: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_update_granted_hub_item_state for super::RemoteReducers {
    fn admin_update_granted_hub_item_state_then(
        &self,
        identity: __sdk::Identity,
item_type: HubItemType,
item_id: i32,
balance: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdminUpdateGrantedHubItemStateArgs { identity, item_type, item_id, balance,  }, callback)
    }
}

