// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminAddOrUpdateModerationViolationArgs {
    pub violation_type: u8,
    pub point_value_min: i32,
    pub point_value_max: i32,
}

impl From<AdminAddOrUpdateModerationViolationArgs> for super::Reducer {
    fn from(args: AdminAddOrUpdateModerationViolationArgs) -> Self {
        Self::AdminAddOrUpdateModerationViolation {
            violation_type: args.violation_type,
            point_value_min: args.point_value_min,
            point_value_max: args.point_value_max,
        }
    }
}

impl __sdk::InModule for AdminAddOrUpdateModerationViolationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_add_or_update_moderation_violation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_add_or_update_moderation_violation {
    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_violation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_add_or_update_moderation_violation:admin_add_or_update_moderation_violation_then`] to run a callback after the reducer completes.
    fn admin_add_or_update_moderation_violation(
        &self,
        violation_type: u8,
        point_value_min: i32,
        point_value_max: i32,
    ) -> __sdk::Result<()> {
        self.admin_add_or_update_moderation_violation_then(
            violation_type,
            point_value_min,
            point_value_max,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `admin_add_or_update_moderation_violation` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_add_or_update_moderation_violation_then(
        &self,
        violation_type: u8,
        point_value_min: i32,
        point_value_max: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_add_or_update_moderation_violation for super::RemoteReducers {
    fn admin_add_or_update_moderation_violation_then(
        &self,
        violation_type: u8,
        point_value_min: i32,
        point_value_max: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminAddOrUpdateModerationViolationArgs {
                violation_type,
                point_value_min,
                point_value_max,
            },
            callback,
        )
    }
}
