// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BlockIdentityArgs {
    pub identity: String,
}

impl From<BlockIdentityArgs> for super::Reducer {
    fn from(args: BlockIdentityArgs) -> Self {
        Self::BlockIdentity {
            identity: args.identity,
}
}
}

impl __sdk::InModule for BlockIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `block_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait block_identity {
    /// Request that the remote module invoke the reducer `block_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`block_identity:block_identity_then`] to run a callback after the reducer completes.
    fn block_identity(&self, identity: String,
) -> __sdk::Result<()> {
        self.block_identity_then(identity,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `block_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn block_identity_then(
        &self,
        identity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl block_identity for super::RemoteReducers {
    fn block_identity_then(
        &self,
        identity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(BlockIdentityArgs { identity,  }, callback)
    }
}

