// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BlockPlayerArgs {
    pub player_entity_id: u64,
}

impl From<BlockPlayerArgs> for super::Reducer {
    fn from(args: BlockPlayerArgs) -> Self {
        Self::BlockPlayer {
            player_entity_id: args.player_entity_id,
}
}
}

impl __sdk::InModule for BlockPlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `block_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait block_player {
    /// Request that the remote module invoke the reducer `block_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`block_player:block_player_then`] to run a callback after the reducer completes.
    fn block_player(&self, player_entity_id: u64,
) -> __sdk::Result<()> {
        self.block_player_then(player_entity_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `block_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn block_player_then(
        &self,
        player_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl block_player for super::RemoteReducers {
    fn block_player_then(
        &self,
        player_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(BlockPlayerArgs { player_entity_id,  }, callback)
    }
}

