// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheatPlayerSetNameArgs {
    pub player_entity_id: u64,
    pub name: String,
}

impl From<CheatPlayerSetNameArgs> for super::Reducer {
    fn from(args: CheatPlayerSetNameArgs) -> Self {
        Self::CheatPlayerSetName {
            player_entity_id: args.player_entity_id,
            name: args.name,
        }
    }
}

impl __sdk::InModule for CheatPlayerSetNameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cheat_player_set_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cheat_player_set_name {
    /// Request that the remote module invoke the reducer `cheat_player_set_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cheat_player_set_name:cheat_player_set_name_then`] to run a callback after the reducer completes.
    fn cheat_player_set_name(&self, player_entity_id: u64, name: String) -> __sdk::Result<()> {
        self.cheat_player_set_name_then(player_entity_id, name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cheat_player_set_name` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cheat_player_set_name_then(
        &self,
        player_entity_id: u64,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cheat_player_set_name for super::RemoteReducers {
    fn cheat_player_set_name_then(
        &self,
        player_entity_id: u64,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CheatPlayerSetNameArgs {
                player_entity_id,
                name,
            },
            callback,
        )
    }
}
