// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheatEmpireSiegeAddSuppliesArgs {
    pub siege_node_entity_id: u64,
    pub supplies: i32,
}

impl From<CheatEmpireSiegeAddSuppliesArgs> for super::Reducer {
    fn from(args: CheatEmpireSiegeAddSuppliesArgs) -> Self {
        Self::CheatEmpireSiegeAddSupplies {
            siege_node_entity_id: args.siege_node_entity_id,
            supplies: args.supplies,
}
}
}

impl __sdk::InModule for CheatEmpireSiegeAddSuppliesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cheat_empire_siege_add_supplies`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cheat_empire_siege_add_supplies {
    /// Request that the remote module invoke the reducer `cheat_empire_siege_add_supplies` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cheat_empire_siege_add_supplies:cheat_empire_siege_add_supplies_then`] to run a callback after the reducer completes.
    fn cheat_empire_siege_add_supplies(&self, siege_node_entity_id: u64,
supplies: i32,
) -> __sdk::Result<()> {
        self.cheat_empire_siege_add_supplies_then(siege_node_entity_id, supplies,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cheat_empire_siege_add_supplies` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cheat_empire_siege_add_supplies_then(
        &self,
        siege_node_entity_id: u64,
supplies: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cheat_empire_siege_add_supplies for super::RemoteReducers {
    fn cheat_empire_siege_add_supplies_then(
        &self,
        siege_node_entity_id: u64,
supplies: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CheatEmpireSiegeAddSuppliesArgs { siege_node_entity_id, supplies,  }, callback)
    }
}

