// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::cheat_shards_grant_request_type::CheatShardsGrantRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheatShardsGrantArgs {
    pub request: CheatShardsGrantRequest,
}

impl From<CheatShardsGrantArgs> for super::Reducer {
    fn from(args: CheatShardsGrantArgs) -> Self {
        Self::CheatShardsGrant {
            request: args.request,
}
}
}

impl __sdk::InModule for CheatShardsGrantArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cheat_shards_grant`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cheat_shards_grant {
    /// Request that the remote module invoke the reducer `cheat_shards_grant` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cheat_shards_grant:cheat_shards_grant_then`] to run a callback after the reducer completes.
    fn cheat_shards_grant(&self, request: CheatShardsGrantRequest,
) -> __sdk::Result<()> {
        self.cheat_shards_grant_then(request,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cheat_shards_grant` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cheat_shards_grant_then(
        &self,
        request: CheatShardsGrantRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cheat_shards_grant for super::RemoteReducers {
    fn cheat_shards_grant_then(
        &self,
        request: CheatShardsGrantRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CheatShardsGrantArgs { request,  }, callback)
    }
}

