// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::combat_action_desc_type::CombatActionDesc;
use super::buff_effect_type::BuffEffect;
use super::level_requirement_type::LevelRequirement;

/// Table handle for the table `combat_action_desc`.
///
/// Obtain a handle from the [`CombatActionDescTableAccess::combat_action_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.combat_action_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_action_desc().on_insert(...)`.
pub struct CombatActionDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<CombatActionDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `combat_action_desc`.
pub struct CombatActionDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CombatActionDescTableAccessor {
    type Row = CombatActionDesc;
    type Handle<'db> = CombatActionDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.combat_action_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `combat_action_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CombatActionDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CombatActionDescTableHandle`], which mediates access to the table `combat_action_desc`.
    fn combat_action_desc(&self) -> CombatActionDescTableHandle<'_>;
}

impl CombatActionDescTableAccess for super::RemoteTables {
    fn combat_action_desc(&self) -> CombatActionDescTableHandle<'_> {
        CombatActionDescTableHandle {
            imp: self.imp.get_table::<CombatActionDesc>("combat_action_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CombatActionDescInsertCallbackId(__sdk::CallbackId);
pub struct CombatActionDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CombatActionDescTableHandle<'ctx> {
    type Row = CombatActionDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CombatActionDesc> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for CombatActionDescTableHandle<'ctx> {
    type Row = CombatActionDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CombatActionDesc> + '_ { self.imp.iter() }

    type InsertCallbackId = CombatActionDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionDescInsertCallbackId {
        CombatActionDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatActionDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CombatActionDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionDescDeleteCallbackId {
        CombatActionDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatActionDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CombatActionDescTableHandle<'ctx> {
    type InsertCallbackId = CombatActionDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionDescInsertCallbackId {
        CombatActionDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatActionDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CombatActionDescTableHandle<'ctx> {
    type DeleteCallbackId = CombatActionDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionDescDeleteCallbackId {
        CombatActionDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatActionDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CombatActionDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CombatActionDescTableHandle<'ctx> {
    type UpdateCallbackId = CombatActionDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatActionDescUpdateCallbackId {
        CombatActionDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatActionDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CombatActionDescTableHandle<'ctx> {
    type UpdateCallbackId = CombatActionDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatActionDescUpdateCallbackId {
        CombatActionDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatActionDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `combat_action_desc`,
        /// which allows point queries on the field of the same name
        /// via the [`CombatActionDescIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.combat_action_desc().id().find(...)`.
        pub struct CombatActionDescIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<CombatActionDesc, i32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> CombatActionDescTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `combat_action_desc`.
            pub fn id(&self) -> CombatActionDescIdUnique<'ctx> {
                CombatActionDescIdUnique {
                    imp: self.imp.get_unique_constraint::<i32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> CombatActionDescIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &i32) -> Option<CombatActionDesc> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<CombatActionDesc>("combat_action_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CombatActionDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<CombatActionDesc>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `CombatActionDesc`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait combat_action_descQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `CombatActionDesc`.
            fn combat_action_desc(&self) -> __sdk::__query_builder::Table<CombatActionDesc>;
        }

        impl combat_action_descQueryTableAccess for __sdk::QueryTableAccessor {
            fn combat_action_desc(&self) -> __sdk::__query_builder::Table<CombatActionDesc> {
                __sdk::__query_builder::Table::new("combat_action_desc")
            }
        }

