// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::combat_action_multi_hit_desc_type::CombatActionMultiHitDesc;
use super::footprint_tile_type::FootprintTile;

/// Table handle for the table `combat_action_multi_hit_desc`.
///
/// Obtain a handle from the [`CombatActionMultiHitDescTableAccess::combat_action_multi_hit_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.combat_action_multi_hit_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_action_multi_hit_desc().on_insert(...)`.
pub struct CombatActionMultiHitDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<CombatActionMultiHitDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `combat_action_multi_hit_desc`.
pub struct CombatActionMultiHitDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CombatActionMultiHitDescTableAccessor {
    type Row = CombatActionMultiHitDesc;
    type Handle<'db> = CombatActionMultiHitDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.combat_action_multi_hit_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `combat_action_multi_hit_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CombatActionMultiHitDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CombatActionMultiHitDescTableHandle`], which mediates access to the table `combat_action_multi_hit_desc`.
    fn combat_action_multi_hit_desc(&self) -> CombatActionMultiHitDescTableHandle<'_>;
}

impl CombatActionMultiHitDescTableAccess for super::RemoteTables {
    fn combat_action_multi_hit_desc(&self) -> CombatActionMultiHitDescTableHandle<'_> {
        CombatActionMultiHitDescTableHandle {
            imp: self.imp.get_table::<CombatActionMultiHitDesc>("combat_action_multi_hit_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CombatActionMultiHitDescInsertCallbackId(__sdk::CallbackId);
pub struct CombatActionMultiHitDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CombatActionMultiHitDescTableHandle<'ctx> {
    type Row = CombatActionMultiHitDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CombatActionMultiHitDesc> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for CombatActionMultiHitDescTableHandle<'ctx> {
    type Row = CombatActionMultiHitDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CombatActionMultiHitDesc> + '_ { self.imp.iter() }

    type InsertCallbackId = CombatActionMultiHitDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionMultiHitDescInsertCallbackId {
        CombatActionMultiHitDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatActionMultiHitDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CombatActionMultiHitDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionMultiHitDescDeleteCallbackId {
        CombatActionMultiHitDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatActionMultiHitDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CombatActionMultiHitDescTableHandle<'ctx> {
    type InsertCallbackId = CombatActionMultiHitDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionMultiHitDescInsertCallbackId {
        CombatActionMultiHitDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatActionMultiHitDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CombatActionMultiHitDescTableHandle<'ctx> {
    type DeleteCallbackId = CombatActionMultiHitDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatActionMultiHitDescDeleteCallbackId {
        CombatActionMultiHitDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatActionMultiHitDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CombatActionMultiHitDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CombatActionMultiHitDescTableHandle<'ctx> {
    type UpdateCallbackId = CombatActionMultiHitDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatActionMultiHitDescUpdateCallbackId {
        CombatActionMultiHitDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatActionMultiHitDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CombatActionMultiHitDescTableHandle<'ctx> {
    type UpdateCallbackId = CombatActionMultiHitDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatActionMultiHitDescUpdateCallbackId {
        CombatActionMultiHitDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatActionMultiHitDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `combat_action_multi_hit_desc`,
        /// which allows point queries on the field of the same name
        /// via the [`CombatActionMultiHitDescIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.combat_action_multi_hit_desc().id().find(...)`.
        pub struct CombatActionMultiHitDescIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<CombatActionMultiHitDesc, i32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> CombatActionMultiHitDescTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `combat_action_multi_hit_desc`.
            pub fn id(&self) -> CombatActionMultiHitDescIdUnique<'ctx> {
                CombatActionMultiHitDescIdUnique {
                    imp: self.imp.get_unique_constraint::<i32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> CombatActionMultiHitDescIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &i32) -> Option<CombatActionMultiHitDesc> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<CombatActionMultiHitDesc>("combat_action_multi_hit_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CombatActionMultiHitDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<CombatActionMultiHitDesc>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `CombatActionMultiHitDesc`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait combat_action_multi_hit_descQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `CombatActionMultiHitDesc`.
            fn combat_action_multi_hit_desc(&self) -> __sdk::__query_builder::Table<CombatActionMultiHitDesc>;
        }

        impl combat_action_multi_hit_descQueryTableAccess for __sdk::QueryTableAccessor {
            fn combat_action_multi_hit_desc(&self) -> __sdk::__query_builder::Table<CombatActionMultiHitDesc> {
                __sdk::__query_builder::Table::new("combat_action_multi_hit_desc")
            }
        }

