// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CorrectTranslationArgs {
    pub string_index: u32,
    pub lang: String,
    pub translation: String,
}

impl From<CorrectTranslationArgs> for super::Reducer {
    fn from(args: CorrectTranslationArgs) -> Self {
        Self::CorrectTranslation {
            string_index: args.string_index,
            lang: args.lang,
            translation: args.translation,
}
}
}

impl __sdk::InModule for CorrectTranslationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `correct_translation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait correct_translation {
    /// Request that the remote module invoke the reducer `correct_translation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`correct_translation:correct_translation_then`] to run a callback after the reducer completes.
    fn correct_translation(&self, string_index: u32,
lang: String,
translation: String,
) -> __sdk::Result<()> {
        self.correct_translation_then(string_index, lang, translation,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `correct_translation` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn correct_translation_then(
        &self,
        string_index: u32,
lang: String,
translation: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl correct_translation for super::RemoteReducers {
    fn correct_translation_then(
        &self,
        string_index: u32,
lang: String,
translation: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CorrectTranslationArgs { string_index, lang, translation,  }, callback)
    }
}

