// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::chat_channel_permission_type::ChatChannelPermission;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EditChatChannelMemberPermissionArgs {
    pub channel_entity_id: u64,
    pub player_entity_id: u64,
    pub rank: ChatChannelPermission,
}

impl From<EditChatChannelMemberPermissionArgs> for super::Reducer {
    fn from(args: EditChatChannelMemberPermissionArgs) -> Self {
        Self::EditChatChannelMemberPermission {
            channel_entity_id: args.channel_entity_id,
            player_entity_id: args.player_entity_id,
            rank: args.rank,
        }
    }
}

impl __sdk::InModule for EditChatChannelMemberPermissionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `edit_chat_channel_member_permission`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait edit_chat_channel_member_permission {
    /// Request that the remote module invoke the reducer `edit_chat_channel_member_permission` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`edit_chat_channel_member_permission:edit_chat_channel_member_permission_then`] to run a callback after the reducer completes.
    fn edit_chat_channel_member_permission(
        &self,
        channel_entity_id: u64,
        player_entity_id: u64,
        rank: ChatChannelPermission,
    ) -> __sdk::Result<()> {
        self.edit_chat_channel_member_permission_then(
            channel_entity_id,
            player_entity_id,
            rank,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `edit_chat_channel_member_permission` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn edit_chat_channel_member_permission_then(
        &self,
        channel_entity_id: u64,
        player_entity_id: u64,
        rank: ChatChannelPermission,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl edit_chat_channel_member_permission for super::RemoteReducers {
    fn edit_chat_channel_member_permission_then(
        &self,
        channel_entity_id: u64,
        player_entity_id: u64,
        rank: ChatChannelPermission,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EditChatChannelMemberPermissionArgs {
                channel_entity_id,
                player_entity_id,
                rank,
            },
            callback,
        )
    }
}
