// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::chat_channel_visibility_type::ChatChannelVisibility;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EditChatChannelArgs {
    pub entity_id: u64,
    pub name: String,
    pub description: String,
    pub visibility: ChatChannelVisibility,
}

impl From<EditChatChannelArgs> for super::Reducer {
    fn from(args: EditChatChannelArgs) -> Self {
        Self::EditChatChannel {
            entity_id: args.entity_id,
            name: args.name,
            description: args.description,
            visibility: args.visibility,
        }
    }
}

impl __sdk::InModule for EditChatChannelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `edit_chat_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait edit_chat_channel {
    /// Request that the remote module invoke the reducer `edit_chat_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`edit_chat_channel:edit_chat_channel_then`] to run a callback after the reducer completes.
    fn edit_chat_channel(
        &self,
        entity_id: u64,
        name: String,
        description: String,
        visibility: ChatChannelVisibility,
    ) -> __sdk::Result<()> {
        self.edit_chat_channel_then(entity_id, name, description, visibility, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `edit_chat_channel` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn edit_chat_channel_then(
        &self,
        entity_id: u64,
        name: String,
        description: String,
        visibility: ChatChannelVisibility,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl edit_chat_channel for super::RemoteReducers {
    fn edit_chat_channel_then(
        &self,
        entity_id: u64,
        name: String,
        description: String,
        visibility: ChatChannelVisibility,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EditChatChannelArgs {
                entity_id,
                name,
                description,
                visibility,
            },
            callback,
        )
    }
}
