// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::empire_dismantle_request_type::EmpireDismantleRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireDismantleArgs {
    pub request: EmpireDismantleRequest,
}

impl From<EmpireDismantleArgs> for super::Reducer {
    fn from(args: EmpireDismantleArgs) -> Self {
        Self::EmpireDismantle {
            request: args.request,
}
}
}

impl __sdk::InModule for EmpireDismantleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_dismantle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_dismantle {
    /// Request that the remote module invoke the reducer `empire_dismantle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_dismantle:empire_dismantle_then`] to run a callback after the reducer completes.
    fn empire_dismantle(&self, request: EmpireDismantleRequest,
) -> __sdk::Result<()> {
        self.empire_dismantle_then(request,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_dismantle` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_dismantle_then(
        &self,
        request: EmpireDismantleRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_dismantle for super::RemoteReducers {
    fn empire_dismantle_then(
        &self,
        request: EmpireDismantleRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(EmpireDismantleArgs { request,  }, callback)
    }
}

