// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireCraftSuppliesArgs {
    pub foundry_entity_id: u64,
}

impl From<EmpireCraftSuppliesArgs> for super::Reducer {
    fn from(args: EmpireCraftSuppliesArgs) -> Self {
        Self::EmpireCraftSupplies {
            foundry_entity_id: args.foundry_entity_id,
        }
    }
}

impl __sdk::InModule for EmpireCraftSuppliesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_craft_supplies`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_craft_supplies {
    /// Request that the remote module invoke the reducer `empire_craft_supplies` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_craft_supplies:empire_craft_supplies_then`] to run a callback after the reducer completes.
    fn empire_craft_supplies(&self, foundry_entity_id: u64) -> __sdk::Result<()> {
        self.empire_craft_supplies_then(foundry_entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_craft_supplies` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_craft_supplies_then(
        &self,
        foundry_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_craft_supplies for super::RemoteReducers {
    fn empire_craft_supplies_then(
        &self,
        foundry_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EmpireCraftSuppliesArgs { foundry_entity_id }, callback)
    }
}
