// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::empire_change_emblem_request_type::EmpireChangeEmblemRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireChangeEmblemArgs {
    pub request: EmpireChangeEmblemRequest,
}

impl From<EmpireChangeEmblemArgs> for super::Reducer {
    fn from(args: EmpireChangeEmblemArgs) -> Self {
        Self::EmpireChangeEmblem {
            request: args.request,
        }
    }
}

impl __sdk::InModule for EmpireChangeEmblemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_change_emblem`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_change_emblem {
    /// Request that the remote module invoke the reducer `empire_change_emblem` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_change_emblem:empire_change_emblem_then`] to run a callback after the reducer completes.
    fn empire_change_emblem(&self, request: EmpireChangeEmblemRequest) -> __sdk::Result<()> {
        self.empire_change_emblem_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_change_emblem` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_change_emblem_then(
        &self,
        request: EmpireChangeEmblemRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_change_emblem for super::RemoteReducers {
    fn empire_change_emblem_then(
        &self,
        request: EmpireChangeEmblemRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EmpireChangeEmblemArgs { request }, callback)
    }
}
