// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireMoveCapitalArgs {
    pub target_claim_entity_id: u64,
}

impl From<EmpireMoveCapitalArgs> for super::Reducer {
    fn from(args: EmpireMoveCapitalArgs) -> Self {
        Self::EmpireMoveCapital {
            target_claim_entity_id: args.target_claim_entity_id,
        }
    }
}

impl __sdk::InModule for EmpireMoveCapitalArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_move_capital`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_move_capital {
    /// Request that the remote module invoke the reducer `empire_move_capital` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_move_capital:empire_move_capital_then`] to run a callback after the reducer completes.
    fn empire_move_capital(&self, target_claim_entity_id: u64) -> __sdk::Result<()> {
        self.empire_move_capital_then(target_claim_entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_move_capital` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_move_capital_then(
        &self,
        target_claim_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_move_capital for super::RemoteReducers {
    fn empire_move_capital_then(
        &self,
        target_claim_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EmpireMoveCapitalArgs {
                target_claim_entity_id,
            },
            callback,
        )
    }
}
