// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::empire_foundry_state_type::EmpireFoundryState;

/// Table handle for the table `empire_foundry_state`.
///
/// Obtain a handle from the [`EmpireFoundryStateTableAccess::empire_foundry_state`] method on [`super::RemoteTables`],
/// like `ctx.db.empire_foundry_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.empire_foundry_state().on_insert(...)`.
pub struct EmpireFoundryStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<EmpireFoundryState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `empire_foundry_state`.
pub struct EmpireFoundryStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for EmpireFoundryStateTableAccessor {
    type Row = EmpireFoundryState;
    type Handle<'db> = EmpireFoundryStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.empire_foundry_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `empire_foundry_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EmpireFoundryStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EmpireFoundryStateTableHandle`], which mediates access to the table `empire_foundry_state`.
    fn empire_foundry_state(&self) -> EmpireFoundryStateTableHandle<'_>;
}

impl EmpireFoundryStateTableAccess for super::RemoteTables {
    fn empire_foundry_state(&self) -> EmpireFoundryStateTableHandle<'_> {
        EmpireFoundryStateTableHandle {
            imp: self.imp.get_table::<EmpireFoundryState>("empire_foundry_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EmpireFoundryStateInsertCallbackId(__sdk::CallbackId);
pub struct EmpireFoundryStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for EmpireFoundryStateTableHandle<'ctx> {
    type Row = EmpireFoundryState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = EmpireFoundryState> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for EmpireFoundryStateTableHandle<'ctx> {
    type Row = EmpireFoundryState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = EmpireFoundryState> + '_ { self.imp.iter() }

    type InsertCallbackId = EmpireFoundryStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireFoundryStateInsertCallbackId {
        EmpireFoundryStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EmpireFoundryStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EmpireFoundryStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireFoundryStateDeleteCallbackId {
        EmpireFoundryStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EmpireFoundryStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for EmpireFoundryStateTableHandle<'ctx> {
    type InsertCallbackId = EmpireFoundryStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireFoundryStateInsertCallbackId {
        EmpireFoundryStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EmpireFoundryStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for EmpireFoundryStateTableHandle<'ctx> {
    type DeleteCallbackId = EmpireFoundryStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireFoundryStateDeleteCallbackId {
        EmpireFoundryStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EmpireFoundryStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EmpireFoundryStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EmpireFoundryStateTableHandle<'ctx> {
    type UpdateCallbackId = EmpireFoundryStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EmpireFoundryStateUpdateCallbackId {
        EmpireFoundryStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EmpireFoundryStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for EmpireFoundryStateTableHandle<'ctx> {
    type UpdateCallbackId = EmpireFoundryStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EmpireFoundryStateUpdateCallbackId {
        EmpireFoundryStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EmpireFoundryStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `entity_id` unique index on the table `empire_foundry_state`,
        /// which allows point queries on the field of the same name
        /// via the [`EmpireFoundryStateEntityIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.empire_foundry_state().entity_id().find(...)`.
        pub struct EmpireFoundryStateEntityIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<EmpireFoundryState, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> EmpireFoundryStateTableHandle<'ctx> {
            /// Get a handle on the `entity_id` unique index on the table `empire_foundry_state`.
            pub fn entity_id(&self) -> EmpireFoundryStateEntityIdUnique<'ctx> {
                EmpireFoundryStateEntityIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("entity_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> EmpireFoundryStateEntityIdUnique<'ctx> {
            /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<EmpireFoundryState> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<EmpireFoundryState>("empire_foundry_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EmpireFoundryState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<EmpireFoundryState>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `EmpireFoundryState`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait empire_foundry_stateQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `EmpireFoundryState`.
            fn empire_foundry_state(&self) -> __sdk::__query_builder::Table<EmpireFoundryState>;
        }

        impl empire_foundry_stateQueryTableAccess for __sdk::QueryTableAccessor {
            fn empire_foundry_state(&self) -> __sdk::__query_builder::Table<EmpireFoundryState> {
                __sdk::__query_builder::Table::new("empire_foundry_state")
            }
        }

