// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::empire_set_directive_message_request_type::EmpireSetDirectiveMessageRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireSetDirectiveMessageArgs {
    pub request: EmpireSetDirectiveMessageRequest,
}

impl From<EmpireSetDirectiveMessageArgs> for super::Reducer {
    fn from(args: EmpireSetDirectiveMessageArgs) -> Self {
        Self::EmpireSetDirectiveMessage {
            request: args.request,
}
}
}

impl __sdk::InModule for EmpireSetDirectiveMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_set_directive_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_set_directive_message {
    /// Request that the remote module invoke the reducer `empire_set_directive_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_set_directive_message:empire_set_directive_message_then`] to run a callback after the reducer completes.
    fn empire_set_directive_message(&self, request: EmpireSetDirectiveMessageRequest,
) -> __sdk::Result<()> {
        self.empire_set_directive_message_then(request,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_set_directive_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_set_directive_message_then(
        &self,
        request: EmpireSetDirectiveMessageRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_set_directive_message for super::RemoteReducers {
    fn empire_set_directive_message_then(
        &self,
        request: EmpireSetDirectiveMessageRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(EmpireSetDirectiveMessageArgs { request,  }, callback)
    }
}

