// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::empire_donate_shards_request_type::EmpireDonateShardsRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireDonateShardsArgs {
    pub request: EmpireDonateShardsRequest,
}

impl From<EmpireDonateShardsArgs> for super::Reducer {
    fn from(args: EmpireDonateShardsArgs) -> Self {
        Self::EmpireDonateShards {
            request: args.request,
}
}
}

impl __sdk::InModule for EmpireDonateShardsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_donate_shards`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_donate_shards {
    /// Request that the remote module invoke the reducer `empire_donate_shards` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_donate_shards:empire_donate_shards_then`] to run a callback after the reducer completes.
    fn empire_donate_shards(&self, request: EmpireDonateShardsRequest,
) -> __sdk::Result<()> {
        self.empire_donate_shards_then(request,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_donate_shards` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_donate_shards_then(
        &self,
        request: EmpireDonateShardsRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_donate_shards for super::RemoteReducers {
    fn empire_donate_shards_then(
        &self,
        request: EmpireDonateShardsRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(EmpireDonateShardsArgs { request,  }, callback)
    }
}

