// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::empire_leave_request_type::EmpireLeaveRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireLeaveArgs {
    pub request: EmpireLeaveRequest,
}

impl From<EmpireLeaveArgs> for super::Reducer {
    fn from(args: EmpireLeaveArgs) -> Self {
        Self::EmpireLeave {
            request: args.request,
}
}
}

impl __sdk::InModule for EmpireLeaveArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_leave`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_leave {
    /// Request that the remote module invoke the reducer `empire_leave` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_leave:empire_leave_then`] to run a callback after the reducer completes.
    fn empire_leave(&self, request: EmpireLeaveRequest,
) -> __sdk::Result<()> {
        self.empire_leave_then(request,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_leave` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_leave_then(
        &self,
        request: EmpireLeaveRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_leave for super::RemoteReducers {
    fn empire_leave_then(
        &self,
        request: EmpireLeaveRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(EmpireLeaveArgs { request,  }, callback)
    }
}

