// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::empire_update_permissions_request_type::EmpireUpdatePermissionsRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireUpdatePermissionsArgs {
    pub request: EmpireUpdatePermissionsRequest,
}

impl From<EmpireUpdatePermissionsArgs> for super::Reducer {
    fn from(args: EmpireUpdatePermissionsArgs) -> Self {
        Self::EmpireUpdatePermissions {
            request: args.request,
        }
    }
}

impl __sdk::InModule for EmpireUpdatePermissionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_update_permissions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_update_permissions {
    /// Request that the remote module invoke the reducer `empire_update_permissions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_update_permissions:empire_update_permissions_then`] to run a callback after the reducer completes.
    fn empire_update_permissions(
        &self,
        request: EmpireUpdatePermissionsRequest,
    ) -> __sdk::Result<()> {
        self.empire_update_permissions_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_update_permissions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_update_permissions_then(
        &self,
        request: EmpireUpdatePermissionsRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_update_permissions for super::RemoteReducers {
    fn empire_update_permissions_then(
        &self,
        request: EmpireUpdatePermissionsRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EmpireUpdatePermissionsArgs { request }, callback)
    }
}
