// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireTransferWatchtowerOwnershipArgs {
    pub watchtower_entity_id: u64,
    pub target_empire_entity_id: u64,
}

impl From<EmpireTransferWatchtowerOwnershipArgs> for super::Reducer {
    fn from(args: EmpireTransferWatchtowerOwnershipArgs) -> Self {
        Self::EmpireTransferWatchtowerOwnership {
            watchtower_entity_id: args.watchtower_entity_id,
            target_empire_entity_id: args.target_empire_entity_id,
        }
    }
}

impl __sdk::InModule for EmpireTransferWatchtowerOwnershipArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_transfer_watchtower_ownership`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_transfer_watchtower_ownership {
    /// Request that the remote module invoke the reducer `empire_transfer_watchtower_ownership` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_transfer_watchtower_ownership:empire_transfer_watchtower_ownership_then`] to run a callback after the reducer completes.
    fn empire_transfer_watchtower_ownership(
        &self,
        watchtower_entity_id: u64,
        target_empire_entity_id: u64,
    ) -> __sdk::Result<()> {
        self.empire_transfer_watchtower_ownership_then(
            watchtower_entity_id,
            target_empire_entity_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `empire_transfer_watchtower_ownership` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_transfer_watchtower_ownership_then(
        &self,
        watchtower_entity_id: u64,
        target_empire_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_transfer_watchtower_ownership for super::RemoteReducers {
    fn empire_transfer_watchtower_ownership_then(
        &self,
        watchtower_entity_id: u64,
        target_empire_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EmpireTransferWatchtowerOwnershipArgs {
                watchtower_entity_id,
                target_empire_entity_id,
            },
            callback,
        )
    }
}
