// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::player_vote_state_type::PlayerVoteState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportPlayerVoteStateArgs {
    pub records: Vec::<PlayerVoteState>,
}

impl From<ImportPlayerVoteStateArgs> for super::Reducer {
    fn from(args: ImportPlayerVoteStateArgs) -> Self {
        Self::ImportPlayerVoteState {
            records: args.records,
}
}
}

impl __sdk::InModule for ImportPlayerVoteStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_player_vote_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_player_vote_state {
    /// Request that the remote module invoke the reducer `import_player_vote_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`import_player_vote_state:import_player_vote_state_then`] to run a callback after the reducer completes.
    fn import_player_vote_state(&self, records: Vec::<PlayerVoteState>,
) -> __sdk::Result<()> {
        self.import_player_vote_state_then(records,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `import_player_vote_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn import_player_vote_state_then(
        &self,
        records: Vec::<PlayerVoteState>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl import_player_vote_state for super::RemoteReducers {
    fn import_player_vote_state_then(
        &self,
        records: Vec::<PlayerVoteState>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ImportPlayerVoteStateArgs { records,  }, callback)
    }
}

