// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::region_connection_info_type::RegionConnectionInfo;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportRegionConnectionInfoArgs {
    pub records: Vec::<RegionConnectionInfo>,
}

impl From<ImportRegionConnectionInfoArgs> for super::Reducer {
    fn from(args: ImportRegionConnectionInfoArgs) -> Self {
        Self::ImportRegionConnectionInfo {
            records: args.records,
}
}
}

impl __sdk::InModule for ImportRegionConnectionInfoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_region_connection_info`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_region_connection_info {
    /// Request that the remote module invoke the reducer `import_region_connection_info` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`import_region_connection_info:import_region_connection_info_then`] to run a callback after the reducer completes.
    fn import_region_connection_info(&self, records: Vec::<RegionConnectionInfo>,
) -> __sdk::Result<()> {
        self.import_region_connection_info_then(records,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `import_region_connection_info` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn import_region_connection_info_then(
        &self,
        records: Vec::<RegionConnectionInfo>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl import_region_connection_info for super::RemoteReducers {
    fn import_region_connection_info_then(
        &self,
        records: Vec::<RegionConnectionInfo>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ImportRegionConnectionInfoArgs { records,  }, callback)
    }
}

