// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LogPlayerWithArgs {}

impl From<LogPlayerWithArgs> for super::Reducer {
    fn from(args: LogPlayerWithArgs) -> Self {
        Self::LogPlayerWith
    }
}

impl __sdk::InModule for LogPlayerWithArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `log_player_with_`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait log_player_with {
    /// Request that the remote module invoke the reducer `log_player_with_` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`log_player_with:log_player_with_then`] to run a callback after the reducer completes.
    fn log_player_with(&self) -> __sdk::Result<()> {
        self.log_player_with_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `log_player_with_` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn log_player_with_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl log_player_with for super::RemoteReducers {
    fn log_player_with_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(LogPlayerWithArgs {}, callback)
    }
}
