// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MigrateFixEmpireLowercaseNamesArgs {}

impl From<MigrateFixEmpireLowercaseNamesArgs> for super::Reducer {
    fn from(args: MigrateFixEmpireLowercaseNamesArgs) -> Self {
        Self::MigrateFixEmpireLowercaseNames
    }
}

impl __sdk::InModule for MigrateFixEmpireLowercaseNamesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `migrate_fix_empire_lowercase_names`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait migrate_fix_empire_lowercase_names {
    /// Request that the remote module invoke the reducer `migrate_fix_empire_lowercase_names` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`migrate_fix_empire_lowercase_names:migrate_fix_empire_lowercase_names_then`] to run a callback after the reducer completes.
    fn migrate_fix_empire_lowercase_names(&self) -> __sdk::Result<()> {
        self.migrate_fix_empire_lowercase_names_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `migrate_fix_empire_lowercase_names` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn migrate_fix_empire_lowercase_names_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl migrate_fix_empire_lowercase_names for super::RemoteReducers {
    fn migrate_fix_empire_lowercase_names_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MigrateFixEmpireLowercaseNamesArgs {}, callback)
    }
}
