// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PurchasePremiumItemArgs {
    pub premium_item_desc_id: i32,
}

impl From<PurchasePremiumItemArgs> for super::Reducer {
    fn from(args: PurchasePremiumItemArgs) -> Self {
        Self::PurchasePremiumItem {
            premium_item_desc_id: args.premium_item_desc_id,
        }
    }
}

impl __sdk::InModule for PurchasePremiumItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `purchase_premium_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait purchase_premium_item {
    /// Request that the remote module invoke the reducer `purchase_premium_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`purchase_premium_item:purchase_premium_item_then`] to run a callback after the reducer completes.
    fn purchase_premium_item(&self, premium_item_desc_id: i32) -> __sdk::Result<()> {
        self.purchase_premium_item_then(premium_item_desc_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `purchase_premium_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn purchase_premium_item_then(
        &self,
        premium_item_desc_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl purchase_premium_item for super::RemoteReducers {
    fn purchase_premium_item_then(
        &self,
        premium_item_desc_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PurchasePremiumItemArgs {
                premium_item_desc_id,
            },
            callback,
        )
    }
}
