// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PurchaseCharacterRenameArgs {
    pub premium_service_desc_id: i32,
    pub new_character_name: String,
}

impl From<PurchaseCharacterRenameArgs> for super::Reducer {
    fn from(args: PurchaseCharacterRenameArgs) -> Self {
        Self::PurchaseCharacterRename {
            premium_service_desc_id: args.premium_service_desc_id,
            new_character_name: args.new_character_name,
}
}
}

impl __sdk::InModule for PurchaseCharacterRenameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `purchase_character_rename`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait purchase_character_rename {
    /// Request that the remote module invoke the reducer `purchase_character_rename` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`purchase_character_rename:purchase_character_rename_then`] to run a callback after the reducer completes.
    fn purchase_character_rename(&self, premium_service_desc_id: i32,
new_character_name: String,
) -> __sdk::Result<()> {
        self.purchase_character_rename_then(premium_service_desc_id, new_character_name,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `purchase_character_rename` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn purchase_character_rename_then(
        &self,
        premium_service_desc_id: i32,
new_character_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl purchase_character_rename for super::RemoteReducers {
    fn purchase_character_rename_then(
        &self,
        premium_service_desc_id: i32,
new_character_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PurchaseCharacterRenameArgs { premium_service_desc_id, new_character_name,  }, callback)
    }
}

