// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::quest_chain_desc_type::QuestChainDesc;
use super::quest_requirement_type::QuestRequirement;
use super::quest_reward_type::QuestReward;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `quest_chain_desc`.
///
/// Obtain a handle from the [`QuestChainDescTableAccess::quest_chain_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.quest_chain_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quest_chain_desc().on_insert(...)`.
pub struct QuestChainDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<QuestChainDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `quest_chain_desc`.
pub struct QuestChainDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for QuestChainDescTableAccessor {
    type Row = QuestChainDesc;
    type Handle<'db> = QuestChainDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.quest_chain_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `quest_chain_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QuestChainDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QuestChainDescTableHandle`], which mediates access to the table `quest_chain_desc`.
    fn quest_chain_desc(&self) -> QuestChainDescTableHandle<'_>;
}

impl QuestChainDescTableAccess for super::RemoteTables {
    fn quest_chain_desc(&self) -> QuestChainDescTableHandle<'_> {
        QuestChainDescTableHandle {
            imp: self.imp.get_table::<QuestChainDesc>("quest_chain_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QuestChainDescInsertCallbackId(__sdk::CallbackId);
pub struct QuestChainDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for QuestChainDescTableHandle<'ctx> {
    type Row = QuestChainDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QuestChainDesc> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for QuestChainDescTableHandle<'ctx> {
    type Row = QuestChainDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QuestChainDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QuestChainDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestChainDescInsertCallbackId {
        QuestChainDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QuestChainDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QuestChainDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestChainDescDeleteCallbackId {
        QuestChainDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QuestChainDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for QuestChainDescTableHandle<'ctx> {
    type InsertCallbackId = QuestChainDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestChainDescInsertCallbackId {
        QuestChainDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QuestChainDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for QuestChainDescTableHandle<'ctx> {
    type DeleteCallbackId = QuestChainDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestChainDescDeleteCallbackId {
        QuestChainDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QuestChainDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct QuestChainDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QuestChainDescTableHandle<'ctx> {
    type UpdateCallbackId = QuestChainDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QuestChainDescUpdateCallbackId {
        QuestChainDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QuestChainDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for QuestChainDescTableHandle<'ctx> {
    type UpdateCallbackId = QuestChainDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QuestChainDescUpdateCallbackId {
        QuestChainDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QuestChainDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `quest_chain_desc`,
/// which allows point queries on the field of the same name
/// via the [`QuestChainDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quest_chain_desc().id().find(...)`.
pub struct QuestChainDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<QuestChainDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QuestChainDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `quest_chain_desc`.
    pub fn id(&self) -> QuestChainDescIdUnique<'ctx> {
        QuestChainDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QuestChainDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<QuestChainDesc> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<QuestChainDesc>("quest_chain_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<QuestChainDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<QuestChainDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `QuestChainDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait quest_chain_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `QuestChainDesc`.
    fn quest_chain_desc(&self) -> __sdk::__query_builder::Table<QuestChainDesc>;
}

impl quest_chain_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn quest_chain_desc(&self) -> __sdk::__query_builder::Table<QuestChainDesc> {
        __sdk::__query_builder::Table::new("quest_chain_desc")
    }
}
