// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveChatChannelArgs {
    pub entity_id: u64,
}

impl From<RemoveChatChannelArgs> for super::Reducer {
    fn from(args: RemoveChatChannelArgs) -> Self {
        Self::RemoveChatChannel {
            entity_id: args.entity_id,
        }
    }
}

impl __sdk::InModule for RemoveChatChannelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_chat_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_chat_channel {
    /// Request that the remote module invoke the reducer `remove_chat_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`remove_chat_channel:remove_chat_channel_then`] to run a callback after the reducer completes.
    fn remove_chat_channel(&self, entity_id: u64) -> __sdk::Result<()> {
        self.remove_chat_channel_then(entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `remove_chat_channel` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn remove_chat_channel_then(
        &self,
        entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl remove_chat_channel for super::RemoteReducers {
    fn remove_chat_channel_then(
        &self,
        entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RemoveChatChannelArgs { entity_id }, callback)
    }
}
