// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportTargetedChatMessageArgs {
    pub chat_message_id: u64,
    pub report_type: String,
    pub message: String,
}

impl From<ReportTargetedChatMessageArgs> for super::Reducer {
    fn from(args: ReportTargetedChatMessageArgs) -> Self {
        Self::ReportTargetedChatMessage {
            chat_message_id: args.chat_message_id,
            report_type: args.report_type,
            message: args.message,
        }
    }
}

impl __sdk::InModule for ReportTargetedChatMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_targeted_chat_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_targeted_chat_message {
    /// Request that the remote module invoke the reducer `report_targeted_chat_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`report_targeted_chat_message:report_targeted_chat_message_then`] to run a callback after the reducer completes.
    fn report_targeted_chat_message(
        &self,
        chat_message_id: u64,
        report_type: String,
        message: String,
    ) -> __sdk::Result<()> {
        self.report_targeted_chat_message_then(chat_message_id, report_type, message, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `report_targeted_chat_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn report_targeted_chat_message_then(
        &self,
        chat_message_id: u64,
        report_type: String,
        message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl report_targeted_chat_message for super::RemoteReducers {
    fn report_targeted_chat_message_then(
        &self,
        chat_message_id: u64,
        report_type: String,
        message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ReportTargetedChatMessageArgs {
                chat_message_id,
                report_type,
                message,
            },
            callback,
        )
    }
}
