// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::visibility_type_type::VisibilityType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetVisibilityArgs {
    pub visibility: VisibilityType,
}

impl From<SetVisibilityArgs> for super::Reducer {
    fn from(args: SetVisibilityArgs) -> Self {
        Self::SetVisibility {
            visibility: args.visibility,
        }
    }
}

impl __sdk::InModule for SetVisibilityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_visibility`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_visibility {
    /// Request that the remote module invoke the reducer `set_visibility` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_visibility:set_visibility_then`] to run a callback after the reducer completes.
    fn set_visibility(&self, visibility: VisibilityType) -> __sdk::Result<()> {
        self.set_visibility_then(visibility, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_visibility` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_visibility_then(
        &self,
        visibility: VisibilityType,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_visibility for super::RemoteReducers {
    fn set_visibility_then(
        &self,
        visibility: VisibilityType,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetVisibilityArgs { visibility }, callback)
    }
}
