// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::role_type::Role;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetRoleForIdentityArgs {
    pub identity: String,
    pub role: Role,
}

impl From<SetRoleForIdentityArgs> for super::Reducer {
    fn from(args: SetRoleForIdentityArgs) -> Self {
        Self::SetRoleForIdentity {
            identity: args.identity,
            role: args.role,
        }
    }
}

impl __sdk::InModule for SetRoleForIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_role_for_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_role_for_identity {
    /// Request that the remote module invoke the reducer `set_role_for_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_role_for_identity:set_role_for_identity_then`] to run a callback after the reducer completes.
    fn set_role_for_identity(&self, identity: String, role: Role) -> __sdk::Result<()> {
        self.set_role_for_identity_then(identity, role, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_role_for_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_role_for_identity_then(
        &self,
        identity: String,
        role: Role,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_role_for_identity for super::RemoteReducers {
    fn set_role_for_identity_then(
        &self,
        identity: String,
        role: Role,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetRoleForIdentityArgs { identity, role }, callback)
    }
}
