// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TranslationCorrections {
    pub id: u64,
    pub string_index: u32,
    pub player_entity_id: u64,
    pub lang: String,
    pub translation: String,
}

impl __sdk::InModule for TranslationCorrections {
    type Module = super::RemoteModule;
}
