// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::role_type::Role;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateRoleForPlayerArgs {
    pub player_entity_id: u64,
    pub role: Role,
}

impl From<UpdateRoleForPlayerArgs> for super::Reducer {
    fn from(args: UpdateRoleForPlayerArgs) -> Self {
        Self::UpdateRoleForPlayer {
            player_entity_id: args.player_entity_id,
            role: args.role,
}
}
}

impl __sdk::InModule for UpdateRoleForPlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_role_for_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_role_for_player {
    /// Request that the remote module invoke the reducer `update_role_for_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_role_for_player:update_role_for_player_then`] to run a callback after the reducer completes.
    fn update_role_for_player(&self, player_entity_id: u64,
role: Role,
) -> __sdk::Result<()> {
        self.update_role_for_player_then(player_entity_id, role,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_role_for_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_role_for_player_then(
        &self,
        player_entity_id: u64,
role: Role,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_role_for_player for super::RemoteReducers {
    fn update_role_for_player_then(
        &self,
        player_entity_id: u64,
role: Role,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(UpdateRoleForPlayerArgs { player_entity_id, role,  }, callback)
    }
}

