// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::user_moderation_create_user_policy_request_type::UserModerationCreateUserPolicyRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UserModerationClearAllArgs {
    pub request: UserModerationCreateUserPolicyRequest,
}

impl From<UserModerationClearAllArgs> for super::Reducer {
    fn from(args: UserModerationClearAllArgs) -> Self {
        Self::UserModerationClearAll {
            request: args.request,
        }
    }
}

impl __sdk::InModule for UserModerationClearAllArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `user_moderation_clear_all`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait user_moderation_clear_all {
    /// Request that the remote module invoke the reducer `user_moderation_clear_all` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`user_moderation_clear_all:user_moderation_clear_all_then`] to run a callback after the reducer completes.
    fn user_moderation_clear_all(
        &self,
        request: UserModerationCreateUserPolicyRequest,
    ) -> __sdk::Result<()> {
        self.user_moderation_clear_all_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `user_moderation_clear_all` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn user_moderation_clear_all_then(
        &self,
        request: UserModerationCreateUserPolicyRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl user_moderation_clear_all for super::RemoteReducers {
    fn user_moderation_clear_all_then(
        &self,
        request: UserModerationCreateUserPolicyRequest,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UserModerationClearAllArgs { request }, callback)
    }
}
