// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::wind_params_desc_type::WindParamsDesc;

/// Table handle for the table `wind_params_desc`.
///
/// Obtain a handle from the [`WindParamsDescTableAccess::wind_params_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.wind_params_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.wind_params_desc().on_insert(...)`.
pub struct WindParamsDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<WindParamsDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `wind_params_desc`.
pub struct WindParamsDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WindParamsDescTableAccessor {
    type Row = WindParamsDesc;
    type Handle<'db> = WindParamsDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.wind_params_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `wind_params_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WindParamsDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WindParamsDescTableHandle`], which mediates access to the table `wind_params_desc`.
    fn wind_params_desc(&self) -> WindParamsDescTableHandle<'_>;
}

impl WindParamsDescTableAccess for super::RemoteTables {
    fn wind_params_desc(&self) -> WindParamsDescTableHandle<'_> {
        WindParamsDescTableHandle {
            imp: self.imp.get_table::<WindParamsDesc>("wind_params_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WindParamsDescInsertCallbackId(__sdk::CallbackId);
pub struct WindParamsDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WindParamsDescTableHandle<'ctx> {
    type Row = WindParamsDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = WindParamsDesc> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for WindParamsDescTableHandle<'ctx> {
    type Row = WindParamsDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = WindParamsDesc> + '_ { self.imp.iter() }

    type InsertCallbackId = WindParamsDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WindParamsDescInsertCallbackId {
        WindParamsDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WindParamsDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WindParamsDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WindParamsDescDeleteCallbackId {
        WindParamsDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WindParamsDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WindParamsDescTableHandle<'ctx> {
    type InsertCallbackId = WindParamsDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WindParamsDescInsertCallbackId {
        WindParamsDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WindParamsDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WindParamsDescTableHandle<'ctx> {
    type DeleteCallbackId = WindParamsDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WindParamsDescDeleteCallbackId {
        WindParamsDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WindParamsDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WindParamsDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WindParamsDescTableHandle<'ctx> {
    type UpdateCallbackId = WindParamsDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WindParamsDescUpdateCallbackId {
        WindParamsDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WindParamsDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WindParamsDescTableHandle<'ctx> {
    type UpdateCallbackId = WindParamsDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WindParamsDescUpdateCallbackId {
        WindParamsDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WindParamsDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `wind_params_desc`,
        /// which allows point queries on the field of the same name
        /// via the [`WindParamsDescIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.wind_params_desc().id().find(...)`.
        pub struct WindParamsDescIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<WindParamsDesc, i32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> WindParamsDescTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `wind_params_desc`.
            pub fn id(&self) -> WindParamsDescIdUnique<'ctx> {
                WindParamsDescIdUnique {
                    imp: self.imp.get_unique_constraint::<i32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> WindParamsDescIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &i32) -> Option<WindParamsDesc> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<WindParamsDesc>("wind_params_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WindParamsDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<WindParamsDesc>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `WindParamsDesc`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait wind_params_descQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `WindParamsDesc`.
            fn wind_params_desc(&self) -> __sdk::__query_builder::Table<WindParamsDesc>;
        }

        impl wind_params_descQueryTableAccess for __sdk::QueryTableAccessor {
            fn wind_params_desc(&self) -> __sdk::__query_builder::Table<WindParamsDesc> {
                __sdk::__query_builder::Table::new("wind_params_desc")
            }
        }

