// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRewardCollectiblesListToVaultArgs {
    pub collectible_id: Vec<i32>,
}

impl From<AdminRewardCollectiblesListToVaultArgs> for super::Reducer {
    fn from(args: AdminRewardCollectiblesListToVaultArgs) -> Self {
        Self::AdminRewardCollectiblesListToVault {
            collectible_id: args.collectible_id,
        }
    }
}

impl __sdk::InModule for AdminRewardCollectiblesListToVaultArgs {
    type Module = super::RemoteModule;
}

pub struct AdminRewardCollectiblesListToVaultCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_reward_collectibles_list_to_vault`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_reward_collectibles_list_to_vault {
    /// Request that the remote module invoke the reducer `admin_reward_collectibles_list_to_vault` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_reward_collectibles_list_to_vault`] callbacks.
    fn admin_reward_collectibles_list_to_vault(
        &self,
        collectible_id: Vec<i32>,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_reward_collectibles_list_to_vault`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminRewardCollectiblesListToVaultCallbackId`] can be passed to [`Self::remove_on_admin_reward_collectibles_list_to_vault`]
    /// to cancel the callback.
    fn on_admin_reward_collectibles_list_to_vault(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<i32>) + Send + 'static,
    ) -> AdminRewardCollectiblesListToVaultCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_reward_collectibles_list_to_vault`],
    /// causing it not to run in the future.
    fn remove_on_admin_reward_collectibles_list_to_vault(
        &self,
        callback: AdminRewardCollectiblesListToVaultCallbackId,
    );
}

impl admin_reward_collectibles_list_to_vault for super::RemoteReducers {
    fn admin_reward_collectibles_list_to_vault(
        &self,
        collectible_id: Vec<i32>,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "admin_reward_collectibles_list_to_vault",
            AdminRewardCollectiblesListToVaultArgs { collectible_id },
        )
    }
    fn on_admin_reward_collectibles_list_to_vault(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<i32>) + Send + 'static,
    ) -> AdminRewardCollectiblesListToVaultCallbackId {
        AdminRewardCollectiblesListToVaultCallbackId(
            self.imp.on_reducer(
                "admin_reward_collectibles_list_to_vault",
                Box::new(move |ctx: &super::ReducerEventContext| {
                    let super::ReducerEventContext {
                        event:
                            __sdk::ReducerEvent {
                                reducer:
                                    super::Reducer::AdminRewardCollectiblesListToVault {
                                        collectible_id,
                                    },
                                ..
                            },
                        ..
                    } = ctx
                    else {
                        unreachable!()
                    };
                    callback(ctx, collectible_id)
                }),
            ),
        )
    }
    fn remove_on_admin_reward_collectibles_list_to_vault(
        &self,
        callback: AdminRewardCollectiblesListToVaultCallbackId,
    ) {
        self.imp
            .remove_on_reducer("admin_reward_collectibles_list_to_vault", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_reward_collectibles_list_to_vault`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_reward_collectibles_list_to_vault {
    /// Set the call-reducer flags for the reducer `admin_reward_collectibles_list_to_vault` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_reward_collectibles_list_to_vault(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_reward_collectibles_list_to_vault for super::SetReducerFlags {
    fn admin_reward_collectibles_list_to_vault(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("admin_reward_collectibles_list_to_vault", flags);
    }
}
