// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::combat_dimension_state_type::CombatDimensionState;

/// Table handle for the table `combat_dimension_state`.
///
/// Obtain a handle from the [`CombatDimensionStateTableAccess::combat_dimension_state`] method on [`super::RemoteTables`],
/// like `ctx.db.combat_dimension_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_dimension_state().on_insert(...)`.
pub struct CombatDimensionStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<CombatDimensionState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `combat_dimension_state`.
pub struct CombatDimensionStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CombatDimensionStateTableAccessor {
    type Row = CombatDimensionState;
    type Handle<'db> = CombatDimensionStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.combat_dimension_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `combat_dimension_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CombatDimensionStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CombatDimensionStateTableHandle`], which mediates access to the table `combat_dimension_state`.
    fn combat_dimension_state(&self) -> CombatDimensionStateTableHandle<'_>;
}

impl CombatDimensionStateTableAccess for super::RemoteTables {
    fn combat_dimension_state(&self) -> CombatDimensionStateTableHandle<'_> {
        CombatDimensionStateTableHandle {
            imp: self.imp.get_table::<CombatDimensionState>("combat_dimension_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CombatDimensionStateInsertCallbackId(__sdk::CallbackId);
pub struct CombatDimensionStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CombatDimensionStateTableHandle<'ctx> {
    type Row = CombatDimensionState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CombatDimensionState> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for CombatDimensionStateTableHandle<'ctx> {
    type Row = CombatDimensionState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CombatDimensionState> + '_ { self.imp.iter() }

    type InsertCallbackId = CombatDimensionStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatDimensionStateInsertCallbackId {
        CombatDimensionStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatDimensionStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CombatDimensionStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatDimensionStateDeleteCallbackId {
        CombatDimensionStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatDimensionStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CombatDimensionStateTableHandle<'ctx> {
    type InsertCallbackId = CombatDimensionStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatDimensionStateInsertCallbackId {
        CombatDimensionStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatDimensionStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CombatDimensionStateTableHandle<'ctx> {
    type DeleteCallbackId = CombatDimensionStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatDimensionStateDeleteCallbackId {
        CombatDimensionStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatDimensionStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CombatDimensionStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CombatDimensionStateTableHandle<'ctx> {
    type UpdateCallbackId = CombatDimensionStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatDimensionStateUpdateCallbackId {
        CombatDimensionStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatDimensionStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CombatDimensionStateTableHandle<'ctx> {
    type UpdateCallbackId = CombatDimensionStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatDimensionStateUpdateCallbackId {
        CombatDimensionStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatDimensionStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `dimension_id` unique index on the table `combat_dimension_state`,
        /// which allows point queries on the field of the same name
        /// via the [`CombatDimensionStateDimensionIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.combat_dimension_state().dimension_id().find(...)`.
        pub struct CombatDimensionStateDimensionIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<CombatDimensionState, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> CombatDimensionStateTableHandle<'ctx> {
            /// Get a handle on the `dimension_id` unique index on the table `combat_dimension_state`.
            pub fn dimension_id(&self) -> CombatDimensionStateDimensionIdUnique<'ctx> {
                CombatDimensionStateDimensionIdUnique {
                    imp: self.imp.get_unique_constraint::<u32>("dimension_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> CombatDimensionStateDimensionIdUnique<'ctx> {
            /// Find the subscribed row whose `dimension_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<CombatDimensionState> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<CombatDimensionState>("combat_dimension_state");
    _table.add_unique_constraint::<u32>("dimension_id", |row| &row.dimension_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CombatDimensionState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<CombatDimensionState>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `CombatDimensionState`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait combat_dimension_stateQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `CombatDimensionState`.
            fn combat_dimension_state(&self) -> __sdk::__query_builder::Table<CombatDimensionState>;
        }

        impl combat_dimension_stateQueryTableAccess for __sdk::QueryTableAccessor {
            fn combat_dimension_state(&self) -> __sdk::__query_builder::Table<CombatDimensionState> {
                __sdk::__query_builder::Table::new("combat_dimension_state")
            }
        }

