// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::gate_desc_type::GateDesc;

/// Table handle for the table `gate_desc`.
///
/// Obtain a handle from the [`GateDescTableAccess::gate_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.gate_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gate_desc().on_insert(...)`.
pub struct GateDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<GateDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gate_desc`.
pub struct GateDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GateDescTableAccessor {
    type Row = GateDesc;
    type Handle<'db> = GateDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gate_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gate_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GateDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GateDescTableHandle`], which mediates access to the table `gate_desc`.
    fn gate_desc(&self) -> GateDescTableHandle<'_>;
}

impl GateDescTableAccess for super::RemoteTables {
    fn gate_desc(&self) -> GateDescTableHandle<'_> {
        GateDescTableHandle {
            imp: self.imp.get_table::<GateDesc>("gate_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GateDescInsertCallbackId(__sdk::CallbackId);
pub struct GateDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GateDescTableHandle<'ctx> {
    type Row = GateDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = GateDesc> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for GateDescTableHandle<'ctx> {
    type Row = GateDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = GateDesc> + '_ { self.imp.iter() }

    type InsertCallbackId = GateDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GateDescInsertCallbackId {
        GateDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GateDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GateDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GateDescDeleteCallbackId {
        GateDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GateDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GateDescTableHandle<'ctx> {
    type InsertCallbackId = GateDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GateDescInsertCallbackId {
        GateDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GateDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GateDescTableHandle<'ctx> {
    type DeleteCallbackId = GateDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GateDescDeleteCallbackId {
        GateDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GateDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GateDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GateDescTableHandle<'ctx> {
    type UpdateCallbackId = GateDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GateDescUpdateCallbackId {
        GateDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GateDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GateDescTableHandle<'ctx> {
    type UpdateCallbackId = GateDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GateDescUpdateCallbackId {
        GateDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GateDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `building_id` unique index on the table `gate_desc`,
        /// which allows point queries on the field of the same name
        /// via the [`GateDescBuildingIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.gate_desc().building_id().find(...)`.
        pub struct GateDescBuildingIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<GateDesc, i32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> GateDescTableHandle<'ctx> {
            /// Get a handle on the `building_id` unique index on the table `gate_desc`.
            pub fn building_id(&self) -> GateDescBuildingIdUnique<'ctx> {
                GateDescBuildingIdUnique {
                    imp: self.imp.get_unique_constraint::<i32>("building_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> GateDescBuildingIdUnique<'ctx> {
            /// Find the subscribed row whose `building_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &i32) -> Option<GateDesc> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<GateDesc>("gate_desc");
    _table.add_unique_constraint::<i32>("building_id", |row| &row.building_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GateDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<GateDesc>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `GateDesc`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait gate_descQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `GateDesc`.
            fn gate_desc(&self) -> __sdk::__query_builder::Table<GateDesc>;
        }

        impl gate_descQueryTableAccess for __sdk::QueryTableAccessor {
            fn gate_desc(&self) -> __sdk::__query_builder::Table<GateDesc> {
                __sdk::__query_builder::Table::new("gate_desc")
            }
        }

