// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MigrateLuminateCavesArgs {
    pub commit: bool,
}

impl From<MigrateLuminateCavesArgs> for super::Reducer {
    fn from(args: MigrateLuminateCavesArgs) -> Self {
        Self::MigrateLuminateCaves {
            commit: args.commit,
        }
    }
}

impl __sdk::InModule for MigrateLuminateCavesArgs {
    type Module = super::RemoteModule;
}

pub struct MigrateLuminateCavesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `migrate_luminate_caves`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait migrate_luminate_caves {
    /// Request that the remote module invoke the reducer `migrate_luminate_caves` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_migrate_luminate_caves`] callbacks.
    fn migrate_luminate_caves(&self, commit: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `migrate_luminate_caves`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MigrateLuminateCavesCallbackId`] can be passed to [`Self::remove_on_migrate_luminate_caves`]
    /// to cancel the callback.
    fn on_migrate_luminate_caves(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> MigrateLuminateCavesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_migrate_luminate_caves`],
    /// causing it not to run in the future.
    fn remove_on_migrate_luminate_caves(&self, callback: MigrateLuminateCavesCallbackId);
}

impl migrate_luminate_caves for super::RemoteReducers {
    fn migrate_luminate_caves(&self, commit: bool) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "migrate_luminate_caves",
            MigrateLuminateCavesArgs { commit },
        )
    }
    fn on_migrate_luminate_caves(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> MigrateLuminateCavesCallbackId {
        MigrateLuminateCavesCallbackId(self.imp.on_reducer(
            "migrate_luminate_caves",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MigrateLuminateCaves { commit },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, commit)
            }),
        ))
    }
    fn remove_on_migrate_luminate_caves(&self, callback: MigrateLuminateCavesCallbackId) {
        self.imp
            .remove_on_reducer("migrate_luminate_caves", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `migrate_luminate_caves`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_migrate_luminate_caves {
    /// Set the call-reducer flags for the reducer `migrate_luminate_caves` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn migrate_luminate_caves(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_migrate_luminate_caves for super::SetReducerFlags {
    fn migrate_luminate_caves(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("migrate_luminate_caves", flags);
    }
}
