// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::pillar_shaping_desc_type::PillarShapingDesc;
use super::input_item_stack_type::InputItemStack;
use super::experience_stack_f_32_type::ExperienceStackF32;

/// Table handle for the table `pillar_shaping_desc`.
///
/// Obtain a handle from the [`PillarShapingDescTableAccess::pillar_shaping_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.pillar_shaping_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pillar_shaping_desc().on_insert(...)`.
pub struct PillarShapingDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<PillarShapingDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `pillar_shaping_desc`.
pub struct PillarShapingDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PillarShapingDescTableAccessor {
    type Row = PillarShapingDesc;
    type Handle<'db> = PillarShapingDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.pillar_shaping_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pillar_shaping_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PillarShapingDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PillarShapingDescTableHandle`], which mediates access to the table `pillar_shaping_desc`.
    fn pillar_shaping_desc(&self) -> PillarShapingDescTableHandle<'_>;
}

impl PillarShapingDescTableAccess for super::RemoteTables {
    fn pillar_shaping_desc(&self) -> PillarShapingDescTableHandle<'_> {
        PillarShapingDescTableHandle {
            imp: self.imp.get_table::<PillarShapingDesc>("pillar_shaping_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PillarShapingDescInsertCallbackId(__sdk::CallbackId);
pub struct PillarShapingDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PillarShapingDescTableHandle<'ctx> {
    type Row = PillarShapingDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PillarShapingDesc> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for PillarShapingDescTableHandle<'ctx> {
    type Row = PillarShapingDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PillarShapingDesc> + '_ { self.imp.iter() }

    type InsertCallbackId = PillarShapingDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PillarShapingDescInsertCallbackId {
        PillarShapingDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PillarShapingDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PillarShapingDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PillarShapingDescDeleteCallbackId {
        PillarShapingDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PillarShapingDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PillarShapingDescTableHandle<'ctx> {
    type InsertCallbackId = PillarShapingDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PillarShapingDescInsertCallbackId {
        PillarShapingDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PillarShapingDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PillarShapingDescTableHandle<'ctx> {
    type DeleteCallbackId = PillarShapingDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PillarShapingDescDeleteCallbackId {
        PillarShapingDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PillarShapingDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PillarShapingDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PillarShapingDescTableHandle<'ctx> {
    type UpdateCallbackId = PillarShapingDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PillarShapingDescUpdateCallbackId {
        PillarShapingDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PillarShapingDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PillarShapingDescTableHandle<'ctx> {
    type UpdateCallbackId = PillarShapingDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PillarShapingDescUpdateCallbackId {
        PillarShapingDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PillarShapingDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `pillar_shaping_desc`,
        /// which allows point queries on the field of the same name
        /// via the [`PillarShapingDescIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.pillar_shaping_desc().id().find(...)`.
        pub struct PillarShapingDescIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<PillarShapingDesc, i32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> PillarShapingDescTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `pillar_shaping_desc`.
            pub fn id(&self) -> PillarShapingDescIdUnique<'ctx> {
                PillarShapingDescIdUnique {
                    imp: self.imp.get_unique_constraint::<i32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> PillarShapingDescIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &i32) -> Option<PillarShapingDesc> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<PillarShapingDesc>("pillar_shaping_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PillarShapingDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PillarShapingDesc>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `PillarShapingDesc`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait pillar_shaping_descQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `PillarShapingDesc`.
            fn pillar_shaping_desc(&self) -> __sdk::__query_builder::Table<PillarShapingDesc>;
        }

        impl pillar_shaping_descQueryTableAccess for __sdk::QueryTableAccessor {
            fn pillar_shaping_desc(&self) -> __sdk::__query_builder::Table<PillarShapingDesc> {
                __sdk::__query_builder::Table::new("pillar_shaping_desc")
            }
        }

