// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::placeable_interaction_desc_type::PlaceableInteractionDesc;
use super::level_requirement_type::LevelRequirement;
use super::item_stack_type::ItemStack;
use super::tool_requirement_type::ToolRequirement;
use super::input_item_stack_type::InputItemStack;
use super::experience_stack_f_32_type::ExperienceStackF32;
use super::placeable_self_buff_chance_type::PlaceableSelfBuffChance;
use super::placeable_growth_outcome_v_2_type::PlaceableGrowthOutcomeV2;

/// Table handle for the table `placeable_interaction_desc`.
///
/// Obtain a handle from the [`PlaceableInteractionDescTableAccess::placeable_interaction_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.placeable_interaction_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.placeable_interaction_desc().on_insert(...)`.
pub struct PlaceableInteractionDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlaceableInteractionDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `placeable_interaction_desc`.
pub struct PlaceableInteractionDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlaceableInteractionDescTableAccessor {
    type Row = PlaceableInteractionDesc;
    type Handle<'db> = PlaceableInteractionDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.placeable_interaction_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `placeable_interaction_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlaceableInteractionDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlaceableInteractionDescTableHandle`], which mediates access to the table `placeable_interaction_desc`.
    fn placeable_interaction_desc(&self) -> PlaceableInteractionDescTableHandle<'_>;
}

impl PlaceableInteractionDescTableAccess for super::RemoteTables {
    fn placeable_interaction_desc(&self) -> PlaceableInteractionDescTableHandle<'_> {
        PlaceableInteractionDescTableHandle {
            imp: self.imp.get_table::<PlaceableInteractionDesc>("placeable_interaction_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlaceableInteractionDescInsertCallbackId(__sdk::CallbackId);
pub struct PlaceableInteractionDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlaceableInteractionDescTableHandle<'ctx> {
    type Row = PlaceableInteractionDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PlaceableInteractionDesc> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for PlaceableInteractionDescTableHandle<'ctx> {
    type Row = PlaceableInteractionDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PlaceableInteractionDesc> + '_ { self.imp.iter() }

    type InsertCallbackId = PlaceableInteractionDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractionDescInsertCallbackId {
        PlaceableInteractionDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlaceableInteractionDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlaceableInteractionDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractionDescDeleteCallbackId {
        PlaceableInteractionDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlaceableInteractionDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlaceableInteractionDescTableHandle<'ctx> {
    type InsertCallbackId = PlaceableInteractionDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractionDescInsertCallbackId {
        PlaceableInteractionDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlaceableInteractionDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PlaceableInteractionDescTableHandle<'ctx> {
    type DeleteCallbackId = PlaceableInteractionDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractionDescDeleteCallbackId {
        PlaceableInteractionDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlaceableInteractionDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlaceableInteractionDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlaceableInteractionDescTableHandle<'ctx> {
    type UpdateCallbackId = PlaceableInteractionDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractionDescUpdateCallbackId {
        PlaceableInteractionDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlaceableInteractionDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PlaceableInteractionDescTableHandle<'ctx> {
    type UpdateCallbackId = PlaceableInteractionDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractionDescUpdateCallbackId {
        PlaceableInteractionDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlaceableInteractionDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `placeable_interaction_desc`,
        /// which allows point queries on the field of the same name
        /// via the [`PlaceableInteractionDescIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.placeable_interaction_desc().id().find(...)`.
        pub struct PlaceableInteractionDescIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<PlaceableInteractionDesc, i32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> PlaceableInteractionDescTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `placeable_interaction_desc`.
            pub fn id(&self) -> PlaceableInteractionDescIdUnique<'ctx> {
                PlaceableInteractionDescIdUnique {
                    imp: self.imp.get_unique_constraint::<i32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> PlaceableInteractionDescIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &i32) -> Option<PlaceableInteractionDesc> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<PlaceableInteractionDesc>("placeable_interaction_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlaceableInteractionDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PlaceableInteractionDesc>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `PlaceableInteractionDesc`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait placeable_interaction_descQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `PlaceableInteractionDesc`.
            fn placeable_interaction_desc(&self) -> __sdk::__query_builder::Table<PlaceableInteractionDesc>;
        }

        impl placeable_interaction_descQueryTableAccess for __sdk::QueryTableAccessor {
            fn placeable_interaction_desc(&self) -> __sdk::__query_builder::Table<PlaceableInteractionDesc> {
                __sdk::__query_builder::Table::new("placeable_interaction_desc")
            }
        }

