// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::building_placement_type::BuildingPlacement;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldPlaceBuildingRequest {
    pub buildings: Vec<BuildingPlacement>,
    pub construction_recipe_id: i32,
    pub dry_run: bool,
    pub log_results: bool,
    pub ignore_claims: bool,
    pub clear_and_level_ground: bool,
    pub ignore_dimension_rules: bool,
    pub ignore_empire_checks: bool,
}

impl __sdk::InModule for WorldPlaceBuildingRequest {
    type Module = super::RemoteModule;
}
